<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s42row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s42row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s42row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s42row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row6_2' class='padding5' style="display:block">Cómo califica la calidad general de los servicios de Salud que Provee ECOPETROL</div><INPUT type='hidden' name='objVals42row6_' id='objVals42row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals42row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s42row8_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s42row8_2' class='padding5'>Con cuáles de los siguientes canales ha tenido usted contacto con ECOPETROL para realizar una solicitud o requerimiento en temas de salud</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s42row9_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj9' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s42row15_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s42row9_2' class='padding2'>Vía Telefónica a través del contact center de salud. </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s42row10_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj10' value='11' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s42row16_','a2a1');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s42row10_2' class='padding2'>Vía Telefónica en la UNIS - Unidad Integrada de Servicios de Salud o Centro de Atención local en salud. </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s42row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s42row17_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s42row11_2' class='padding2'>De forma presencial en UNIS o Centro de Atención Local en Salud </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s42row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s42row18_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s42row12_2' class='padding2'>Correo electrónico. </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s42row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='40' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s42row19_','a2d');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s42row13_2' class='padding2'>Página web en la sección de salud </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s42row14_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s42row14_2' class='padding5'>Teniendo en cuenta la atención brindada en temas de salud y en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row14_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row15_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row15_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono en el contact center de salud?</div><INPUT type='hidden' name='objVals42row15_' id='objVals42row15_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row15_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals42row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row15_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals42row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row16_1' class='padding5' style="display:none"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row16_2' class='padding5' style="display:none">¿Cómo califica la calidad de atención telefónica en las UNIS o Centro de atención Local?</div><INPUT type='hidden' name='objVals42row16_' id='objVals42row16_' value='1' lang='Por favor responder la pregunta b1' title='a2a1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='01' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='02' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='03' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='04' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='05' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='06' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='07' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='08' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='09' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='10' onClick="marcarSeleccion('objVals42row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a1' id='a2a1' lang='' value='99' onClick="marcarSeleccion('objVals42row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row17_1' class='padding5' style="display:none"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de atención presencial en las UNIS o Centro de atención local?</div><INPUT type='hidden' name='objVals42row17_' id='objVals42row17_' value='1' lang='Por favor responder la pregunta b2' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals42row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals42row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row18_1' class='padding5' style="display:none"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row18_2' class='padding5' style="display:none">¿Cómo califica la calidad de la atención a través de los correos electrónicos?</div><INPUT type='hidden' name='objVals42row18_' id='objVals42row18_' value='1' lang='Por favor responder la pregunta b3' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row18_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals42row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row18_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals42row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row19_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row19_2' class='padding5' style="display:none">¿Cómo califica el portal de la página web en la sección de salud?</div><INPUT type='hidden' name='objVals42row19_' id='objVals42row19_' value='1' lang='Por favor responder la pregunta c' title='a2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row19_3' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='01' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_4' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='02' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_5' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='03' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_6' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='04' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_7' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='05' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_8' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='06' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_9' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='07' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_10' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='08' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_11' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='09' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_12' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='10' onClick="marcarSeleccion('objVals42row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row19_13' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='99' onClick="marcarSeleccion('objVals42row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s42row20_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s42row20_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en relación al servicio de salud de ECOPETROL? Qué le gustaría ver? O Qué está haciendo falta?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s42row21_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s42row21_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row21_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row22_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row22_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los procesos, acuerdos de nivel de servicios o en general el alcance del plan de beneficios del servicio de salud de ECOPETROL?</div><INPUT type='hidden' name='objVals42row22_' id='objVals42row22_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row22_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals42row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row22_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals42row22_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s42row24_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s42row24_2' class='padding5'>En relación con la atención brindada por DHS - Salud, en una escala de 1 a 10 donde 1 es malo y 10 excelente…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row24_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row25_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row25_2' class='padding5' style="display:block">Calidad general los procesos administrativos que hacen parte del servicio que ofrecen las UNIS y Dependencia de Salud de ECOPETROL</div><INPUT type='hidden' name='objVals42row25_' id='objVals42row25_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals42row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals42row25_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s42row26_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s42row26_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row26_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row27_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row27_2' class='padding5' style="display:block">Amabilidad y comunicación de las personas</div><INPUT type='hidden' name='objVals42row27_' id='objVals42row27_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals42row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals42row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row28_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row28_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que atienden</div><INPUT type='hidden' name='objVals42row28_' id='objVals42row28_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals42row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals42row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row29_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row29_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals42row29_' id='objVals42row29_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals42row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals42row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row30_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row30_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals42row30_' id='objVals42row30_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals42row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals42row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row31_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row31_2' class='padding5' style="display:block">Herramientas tecnológicas utilizadas</div><INPUT type='hidden' name='objVals42row31_' id='objVals42row31_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals42row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals42row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row32_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row32_2' class='padding5' style="display:block">Facilidad para la utilización del servicio</div><INPUT type='hidden' name='objVals42row32_' id='objVals42row32_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals42row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals42row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row33_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row33_2' class='padding5' style="display:block">Calidad general de la red de prestadores que atienden a los usuarios del servicio de salud de ECOPETROL</div><INPUT type='hidden' name='objVals42row33_' id='objVals42row33_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row33_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals42row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row33_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals42row33_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s42row34_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s42row34_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s42row34_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row35_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row35_2' class='padding5' style="display:block">Amabilidad y comunicaciones de la red de prestadores de salud</div><INPUT type='hidden' name='objVals42row35_' id='objVals42row35_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row35_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals42row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row35_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals42row35_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row36_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row36_2' class='padding5' style="display:block">Conocimiento, experiencia y calidad técnica de la red de prestadores de salud</div><INPUT type='hidden' name='objVals42row36_' id='objVals42row36_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row36_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals42row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row36_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals42row36_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row37_1' class='padding5' style="display:block"><B>b11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row37_2' class='padding5' style="display:block">Claridad de la información que ofrecen los profesionales de la red de prestadores de salud</div><INPUT type='hidden' name='objVals42row37_' id='objVals42row37_' value='0' lang='Por favor responder la pregunta b11' title='b11'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row37_3' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='01' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_4' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='02' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_5' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='03' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_6' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='04' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_7' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='05' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_8' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='06' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_9' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='07' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_10' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='08' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_11' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='09' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_12' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='10' onClick="marcarSeleccion('objVals42row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row37_13' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='99' onClick="marcarSeleccion('objVals42row37_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row38_1' class='padding5' style="display:block"><B>b12.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row38_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos por parte de la red de prestadores de salud</div><INPUT type='hidden' name='objVals42row38_' id='objVals42row38_' value='0' lang='Por favor responder la pregunta b12' title='b12'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row38_3' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='01' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_4' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='02' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_5' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='03' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_6' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='04' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_7' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='05' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_8' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='06' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_9' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='07' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_10' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='08' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_11' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='09' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_12' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='10' onClick="marcarSeleccion('objVals42row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row38_13' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='99' onClick="marcarSeleccion('objVals42row38_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row39_1' class='padding5' style="display:block"><B>b13.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row39_2' class='padding5' style="display:block">Herramientas tecnológicas utilizadas por la red de prestadores de salud</div><INPUT type='hidden' name='objVals42row39_' id='objVals42row39_' value='0' lang='Por favor responder la pregunta b13' title='b13'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row39_3' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='01' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_4' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='02' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_5' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='03' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_6' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='04' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_7' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='05' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_8' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='06' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_9' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='07' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_10' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='08' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_11' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='09' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_12' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='10' onClick="marcarSeleccion('objVals42row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row39_13' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='99' onClick="marcarSeleccion('objVals42row39_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row40_1' class='padding5' style="display:block"><B>b14.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row40_2' class='padding5' style="display:block">Facilidad de acceso para la utilización del servicio de salud</div><INPUT type='hidden' name='objVals42row40_' id='objVals42row40_' value='0' lang='Por favor responder la pregunta b14' title='b14'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s42row40_3' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='01' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_4' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='02' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_5' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='03' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_6' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='04' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_7' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='05' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_8' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='06' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_9' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='07' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_10' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='08' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_11' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='09' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_12' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='10' onClick="marcarSeleccion('objVals42row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s42row40_13' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='99' onClick="marcarSeleccion('objVals42row40_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row42_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row42_2' class='padding5'>Usted diría que su relación con el servicio de salud de ECOPETROL</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s42row42_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s42row44_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s42row44_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante del servicio de salud de ECOPETROL?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s42row45_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s42row45_3' class='padding5' style="display:block">¿Qué se está haciendo bien en el servicio de salud de ECOPETROL?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s42row46_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s42row46_3' class='padding5' style="display:block">¿Qué se debe mejorar en el servicio de salud de ECOPETROL?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s42row48_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s42row48_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s42row48_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s42row48_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row49_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s42row49_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals42row49_' id='objVals42row49_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s42row49_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals42row49_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s42row49_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals42row49_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>