<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s22row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s22row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL UNIDAD</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s22row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s22row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row6_1' class='padding5' style="display:block"><B>1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row6_2' class='padding5' style="display:block">Cómo califica la calidad general de los SERVICIOS COMPARTIDOS INMOBILIARIOS y ADMINISTRATIVOS</div><INPUT type='hidden' name='objVals22row6_' id='objVals22row6_' value='0' lang='Por favor responder la pregunta 1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals22row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row8_1' class='padding5'><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row8_2' class='padding5'>Sabe usted como comunicarse con el Centro de Servicios Compartidos dado que tenga una observación o una solicitud específica sobre el Servicio de Gestión de Viajes?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s22row8_3' class='padding5'>
				<SELECT name='a11' id='a11' lang='1' title='Por favor responder la pregunta a11' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s22row9_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s22row9_2' class='padding5'>En general su relación con el  Centro de Servicios Compartidos en relación al servicio de Gestión de Viajes es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s22row10_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj10' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s22row16_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s22row10_2' class='padding2'>Teléfono- CONTACT CENTER </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s22row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s22row17_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s22row11_2' class='padding2'>Presencial Proceso de pago de viáticos </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s22row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s22row18_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s22row12_2' class='padding2'>Correo electrónico-cierre de legalización de comisión </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s22row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='40' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s22row19_','a2d');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s22row13_2' class='padding2'>Página de viajes IRIS </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s22row14_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj14' value='41' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s22row20_','a2d1');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s22row14_2' class='padding2'>Viajero (Herramienta de viáticos) </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s22row15_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s22row15_2' class='padding5'>Teniendo en cuenta la atención brindada por el servicio de Gestión de viajes, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row15_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row16_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row16_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono CONTACT CENTER?</div><INPUT type='hidden' name='objVals22row16_' id='objVals22row16_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals22row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals22row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row17_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de la atención presencial del proceso de pago de viáticos?</div><INPUT type='hidden' name='objVals22row17_' id='objVals22row17_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals22row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals22row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row18_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row18_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos para el cierre de legalización de comisiones?</div><INPUT type='hidden' name='objVals22row18_' id='objVals22row18_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row18_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals22row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row18_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals22row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row19_1' class='padding5' style="display:none"><B>d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row19_2' class='padding5' style="display:none">¿Cómo califica la página de viajes IRIS</div><INPUT type='hidden' name='objVals22row19_' id='objVals22row19_' value='1' lang='Por favor responder la pregunta d' title='a2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row19_3' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='01' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_4' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='02' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_5' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='03' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_6' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='04' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_7' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='05' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_8' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='06' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_9' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='07' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_10' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='08' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_11' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='09' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_12' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='10' onClick="marcarSeleccion('objVals22row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row19_13' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='99' onClick="marcarSeleccion('objVals22row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row20_1' class='padding5' style="display:none"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row20_2' class='padding5' style="display:none">¿Cómo califica la herramienta Viajero (Herramienta de viáticos)</div><INPUT type='hidden' name='objVals22row20_' id='objVals22row20_' value='1' lang='Por favor responder la pregunta d1' title='a2d1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row20_3' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='01' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_4' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='02' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_5' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='03' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_6' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='04' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_7' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='05' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_8' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='06' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_9' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='07' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_10' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='08' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_11' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='09' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_12' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='10' onClick="marcarSeleccion('objVals22row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row20_13' class='padding5' style="display:none"><INPUT type='radio' name='a2d1' id='a2d1' lang='' value='99' onClick="marcarSeleccion('objVals22row20_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s22row21_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s22row21_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en relación al Servicio de Gestión de viajes?  Qué le gustaría ver? O Qué está haciendo falta para lograr los objetivos o el cumplimiento de los acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s22row22_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s22row22_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row22_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row23_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row23_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los procesos, acuerdos de nivel de servicios o en general  del Servicio de Gestión de viajes?</div><INPUT type='hidden' name='objVals22row23_' id='objVals22row23_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row23_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals22row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row23_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals22row23_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s22row25_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s22row25_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row25_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row26_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row26_2' class='padding5' style="display:block">Calidad general del Servicio de Gestión de viajes</div><INPUT type='hidden' name='objVals22row26_' id='objVals22row26_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals22row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals22row26_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s22row27_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s22row27_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s22row27_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row28_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row28_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals22row28_' id='objVals22row28_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals22row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals22row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row29_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row29_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que atienden las asesorías y/o consultas de viajes</div><INPUT type='hidden' name='objVals22row29_' id='objVals22row29_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals22row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals22row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row30_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row30_2' class='padding5' style="display:block">Claridad de la información de las publicaciones y noticias</div><INPUT type='hidden' name='objVals22row30_' id='objVals22row30_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals22row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals22row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row31_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row31_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals22row31_' id='objVals22row31_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals22row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals22row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row32_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row32_2' class='padding5' style="display:block">Convenios con los proveedores: hoteles, aerolíneas, rentadoras de autos y tarjetas de asistencia al viajero</div><INPUT type='hidden' name='objVals22row32_' id='objVals22row32_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals22row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals22row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row33_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row33_2' class='padding5' style="display:block">Facilidad con que se realiza el proceso de viajes</div><INPUT type='hidden' name='objVals22row33_' id='objVals22row33_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row33_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals22row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row33_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals22row33_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row34_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row34_2' class='padding5' style="display:block">Utilidad de las noticias publicadas en Iris y/o las noticias por correo de "Notas de Vuelo"</div><INPUT type='hidden' name='objVals22row34_' id='objVals22row34_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s22row34_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals22row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s22row34_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals22row34_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row36_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row36_2' class='padding5'>Usted diría que su relación con el Centro de Servicios Compartidos…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s22row36_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row37_1' class='padding5'><B>c2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row37_2' class='padding5'>Y específicamente usted diría que el  Servicio de Gestión de viajes…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s22row37_3' class='padding5'>
				<SELECT name='c2' id='c2' lang='1' title='Por favor responder la pregunta c2' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s22row39_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s22row39_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante del Servicio de Gestión de viajes?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s22row40_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s22row40_3' class='padding5' style="display:block">¿Qué se está haciendo bien en el Servicio de Gestión de viajes?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s22row41_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s22row41_3' class='padding5' style="display:block">¿Qué se debe mejorar en el Servicio de Gestión de viajes?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row43_1' class='padding5'><B>&nbsp;</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s22row43_2' class='padding5'>Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s22row43_3' class='padding5'>
				<SELECT name='autoriza' id='autoriza' lang='1' title='Por favor responder la pregunta ' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>