<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s28row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s28row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s28row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s28row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row6_2' class='padding5' style="display:block">Cómo califica la calidad general del servicio de gatekeepers que desempeña la Dirección Corporativa de Proyectos DPY</div><INPUT type='hidden' name='objVals28row6_' id='objVals28row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals28row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s28row8_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s28row8_2' class='padding5'>En general su relación con las personas de DPY es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s28row9_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj9' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s28row13_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s28row9_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s28row10_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj10' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s28row14_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s28row10_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s28row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s28row15_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s28row11_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s28row12_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s28row12_2' class='padding5'>Pensando en la atención brindada por DPY, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row12_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row13_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row13_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals28row13_' id='objVals28row13_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row13_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals28row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row13_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals28row13_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row14_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row14_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals28row14_' id='objVals28row14_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row14_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals28row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row14_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals28row14_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row15_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row15_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals28row15_' id='objVals28row15_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row15_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals28row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row15_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals28row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s28row16_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s28row16_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en relación con la labor de gatekeeper que hace DPY? Qué le gustaría ver? O Qué está haciendo falta para lograr los objetivos o el cumplimiento de los acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s28row17_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s28row17_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row17_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row18_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row18_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los procesos, en general a la DPY?</div><INPUT type='hidden' name='objVals28row18_' id='objVals28row18_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row18_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals28row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row18_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals28row18_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s28row20_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s28row20_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row20_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row21_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row21_2' class='padding5' style="display:block">Calidad general de la Gestión de Proyectos que realiza DPY</div><INPUT type='hidden' name='objVals28row21_' id='objVals28row21_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row21_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals28row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row21_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals28row21_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s28row22_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s28row22_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s28row22_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row23_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row23_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals28row23_' id='objVals28row23_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row23_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals28row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row23_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals28row23_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row24_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row24_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals28row24_' id='objVals28row24_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row24_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals28row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row24_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals28row24_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row25_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row25_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals28row25_' id='objVals28row25_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals28row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals28row25_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row26_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row26_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals28row26_' id='objVals28row26_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals28row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals28row26_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row27_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row27_2' class='padding5' style="display:block">Herramientas utilizadas tecnológicas, las mejores prácticas, métodos y/o modelos </div><INPUT type='hidden' name='objVals28row27_' id='objVals28row27_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals28row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals28row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row28_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row28_2' class='padding5' style="display:block">La utilidad de la recomendación dada</div><INPUT type='hidden' name='objVals28row28_' id='objVals28row28_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals28row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals28row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row29_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row29_2' class='padding5' style="display:block">El rol de gatekeeper que realiza</div><INPUT type='hidden' name='objVals28row29_' id='objVals28row29_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals28row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals28row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row30_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row30_2' class='padding5' style="display:block">Alineación y aporte a la maduración</div><INPUT type='hidden' name='objVals28row30_' id='objVals28row30_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals28row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals28row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row31_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row31_2' class='padding5' style="display:block">La contribución que le ha dado a usted en relación a la estructuración de proyectos</div><INPUT type='hidden' name='objVals28row31_' id='objVals28row31_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals28row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals28row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row32_1' class='padding5' style="display:block"><B>b11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row32_2' class='padding5' style="display:block">El apoyo y acompañamiento brindado</div><INPUT type='hidden' name='objVals28row32_' id='objVals28row32_' value='0' lang='Por favor responder la pregunta b11' title='b11'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s28row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='01' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='02' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='03' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='04' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='05' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='06' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='07' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='08' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='09' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='10' onClick="marcarSeleccion('objVals28row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s28row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='99' onClick="marcarSeleccion('objVals28row32_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row34_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row34_2' class='padding5'>Usted diría que su relación con DPY…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s28row34_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s28row36_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s28row36_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante de DPY en su labor de gatekeeper?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s28row37_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s28row37_3' class='padding5' style="display:block">¿Qué se está haciendo bien de DPY en su labor de gatekeeper?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s28row38_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s28row38_3' class='padding5' style="display:block">¿Qué se debe mejorar de DPY en su labor de gatekeeper?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>Perfil demográfico</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s28row40_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s28row40_2' class='padding5'>Cuántos años de experiencia tiene usted en:</div></TD>
			  
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row41_1' class='padding5'><B>1a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row41_2' class='padding5'>Estructuración de proyectos en general</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s28row41_3' class='padding5'>
				<SELECT name='anios_exp_a' id='anios_exp_a' lang='1' title='Por favor responder la pregunta 1a' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='00'>0 Años</OPTION><OPTION value='01'>01 Años</OPTION><OPTION value='02'>02 Años</OPTION><OPTION value='03'>03 Años</OPTION><OPTION value='04'>04 Años</OPTION><OPTION value='05'>05 Años</OPTION><OPTION value='06'>06 Años</OPTION><OPTION value='07'>07 Años</OPTION><OPTION value='08'>08 Años</OPTION><OPTION value='09'>09 Años</OPTION><OPTION value='10'>10 Años</OPTION><OPTION value='11'>11 Años</OPTION><OPTION value='12'>12 Años</OPTION><OPTION value='13'>13 Años</OPTION><OPTION value='14'>14 Años</OPTION><OPTION value='15'>15 Años</OPTION><OPTION value='16'>16 Años</OPTION><OPTION value='17'>17 Años</OPTION><OPTION value='18'>18 Años</OPTION><OPTION value='19'>19 Años</OPTION><OPTION value='20'>20 Años</OPTION><OPTION value='21'>21 Años</OPTION><OPTION value='22'>22 Años</OPTION><OPTION value='23'>23 Años</OPTION><OPTION value='24'>24 Años</OPTION><OPTION value='25'>25 Años</OPTION><OPTION value='26'>26 Años</OPTION><OPTION value='27'>27 Años</OPTION><OPTION value='28'>28 Años</OPTION><OPTION value='29'>29 Años</OPTION><OPTION value='30'>30 Años</OPTION><OPTION value='50'>Más de 30 Años</OPTION>
				</SELECT></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row42_1' class='padding5'><B>1b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row42_2' class='padding5'>Estructuración de proyectos en ECOPETROL</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s28row42_3' class='padding5'>
				<SELECT name='anios_exp_b' id='anios_exp_b' lang='1' title='Por favor responder la pregunta 1b' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='00'>0 Años</OPTION><OPTION value='01'>01 Años</OPTION><OPTION value='02'>02 Años</OPTION><OPTION value='03'>03 Años</OPTION><OPTION value='04'>04 Años</OPTION><OPTION value='05'>05 Años</OPTION><OPTION value='06'>06 Años</OPTION><OPTION value='07'>07 Años</OPTION><OPTION value='08'>08 Años</OPTION><OPTION value='09'>09 Años</OPTION><OPTION value='10'>10 Años</OPTION><OPTION value='11'>11 Años</OPTION><OPTION value='12'>12 Años</OPTION><OPTION value='13'>13 Años</OPTION><OPTION value='14'>14 Años</OPTION><OPTION value='15'>15 Años</OPTION><OPTION value='16'>16 Años</OPTION><OPTION value='17'>17 Años</OPTION><OPTION value='18'>18 Años</OPTION><OPTION value='19'>19 Años</OPTION><OPTION value='20'>20 Años</OPTION><OPTION value='21'>21 Años</OPTION><OPTION value='22'>22 Años</OPTION><OPTION value='23'>23 Años</OPTION><OPTION value='24'>24 Años</OPTION><OPTION value='25'>25 Años</OPTION><OPTION value='26'>26 Años</OPTION><OPTION value='27'>27 Años</OPTION><OPTION value='28'>28 Años</OPTION><OPTION value='29'>29 Años</OPTION><OPTION value='30'>30 Años</OPTION><OPTION value='50'>Más de 30 Años</OPTION>
				</SELECT></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row43_1' class='padding5'><B>1c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row43_2' class='padding5'>Estructuración de proyectos con el Modelo de Maduración de Programas y Proyectos <B>PMP</B></div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s28row43_3' class='padding5'>
				<SELECT name='anios_exp_c' id='anios_exp_c' lang='1' title='Por favor responder la pregunta 1c' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='00'>0 Años</OPTION><OPTION value='01'>01 Años</OPTION><OPTION value='02'>02 Años</OPTION><OPTION value='03'>03 Años</OPTION><OPTION value='04'>04 Años</OPTION><OPTION value='05'>05 Años</OPTION><OPTION value='06'>06 Años</OPTION><OPTION value='07'>07 Años</OPTION><OPTION value='08'>08 Años</OPTION><OPTION value='09'>09 Años</OPTION><OPTION value='10'>10 Años</OPTION><OPTION value='11'>11 Años</OPTION><OPTION value='12'>12 Años</OPTION><OPTION value='13'>13 Años</OPTION><OPTION value='14'>14 Años</OPTION><OPTION value='15'>15 Años</OPTION><OPTION value='16'>16 Años</OPTION><OPTION value='17'>17 Años</OPTION><OPTION value='18'>18 Años</OPTION><OPTION value='19'>19 Años</OPTION><OPTION value='20'>20 Años</OPTION><OPTION value='21'>21 Años</OPTION><OPTION value='22'>22 Años</OPTION><OPTION value='23'>23 Años</OPTION><OPTION value='24'>24 Años</OPTION><OPTION value='25'>25 Años</OPTION><OPTION value='26'>26 Años</OPTION><OPTION value='27'>27 Años</OPTION><OPTION value='28'>28 Años</OPTION><OPTION value='29'>29 Años</OPTION><OPTION value='30'>30 Años</OPTION><OPTION value='50'>Más de 30 Años</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s28row45_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s28row45_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s28row45_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s28row45_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row46_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s28row46_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals28row46_' id='objVals28row46_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s28row46_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals28row46_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s28row46_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals28row46_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>