<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s31row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s31row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s31row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s31row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row6_2' class='padding5' style="display:block">Cómo califica la calidad general del proceso de Nuevos Negocios de Exploración & Producción?</div><INPUT type='hidden' name='objVals31row6_' id='objVals31row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals31row6_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row7_1' class='padding5' style="display:block"><B>g2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row7_2' class='padding5' style="display:block">Cuál es su nivel de Satisfacción respecto a la gestión de Nuevos Negocios de Exploración & Producción?</div><INPUT type='hidden' name='objVals31row7_' id='objVals31row7_' value='0' lang='Por favor responder la pregunta g2' title='g2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row7_3' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='01' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_4' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='02' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_5' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='03' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_6' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='04' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_7' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='05' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_8' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='06' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_9' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='07' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_10' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='08' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_11' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='09' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_12' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='10' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row7_13' class='padding5' style="display:block"><INPUT type='radio' name='g2' id='g2' lang='' value='99' onClick=" marcarSeleccion('objVals31row7_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s31row9_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s31row9_2' class='padding5'>En general su relación con las personas del proceso de Nuevos Negocios de E&P es a través de:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s31row10_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj10' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s31row14_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s31row10_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s31row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s31row15_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s31row11_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s31row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s31row16_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s31row12_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s31row13_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s31row13_2' class='padding5'>Teniendo en cuenta la atención brindada por el personal que hace parte del Proceso de Nuevos Negocios de E&P, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row13_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row14_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row14_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals31row14_' id='objVals31row14_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row14_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals31row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row14_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals31row14_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row15_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row15_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals31row15_' id='objVals31row15_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row15_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals31row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row15_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals31row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row16_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row16_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals31row16_' id='objVals31row16_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals31row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals31row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s31row17_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s31row17_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en el Proceso de Nuevos Negocios de E&P? Qué le gustaría ver? O Qué está haciendo falta para lograr sus objetivos o el cumplimiento de sus acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s31row18_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s31row18_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row18_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row19_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row19_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce el Proceso de Nuevos Negocios E&P?</div><INPUT type='hidden' name='objVals31row19_' id='objVals31row19_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row19_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals31row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row19_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals31row19_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL PROCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s31row21_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s31row21_2' class='padding5'>En Términos generales, como califica usted el Proceso de Nuevos Negocios de E&P en los siguientes aspectos, usando una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row21_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row22_1' class='padding5' style="display:block"><B>b1_1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row22_2' class='padding5' style="display:block">Proceso para toma de decisiones</div><INPUT type='hidden' name='objVals31row22_' id='objVals31row22_' value='0' lang='Por favor responder la pregunta b1_1' title='b1_1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row22_3' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='01' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_4' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='02' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_5' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='03' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_6' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='04' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_7' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='05' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_8' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='06' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_9' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='07' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_10' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='08' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_11' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='09' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_12' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='10' onClick="marcarSeleccion('objVals31row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row22_13' class='padding5' style="display:block"><INPUT type='radio' name='b1_1' id='b1_1' lang='' value='99' onClick="marcarSeleccion('objVals31row22_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row23_1' class='padding5' style="display:block"><B>b2_1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row23_2' class='padding5' style="display:block">Niveles de Delegación y Autoridad</div><INPUT type='hidden' name='objVals31row23_' id='objVals31row23_' value='0' lang='Por favor responder la pregunta b2_1' title='b2_1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row23_3' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='01' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_4' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='02' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_5' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='03' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_6' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='04' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_7' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='05' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_8' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='06' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_9' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='07' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_10' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='08' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_11' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='09' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_12' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='10' onClick="marcarSeleccion('objVals31row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row23_13' class='padding5' style="display:block"><INPUT type='radio' name='b2_1' id='b2_1' lang='' value='99' onClick="marcarSeleccion('objVals31row23_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row24_1' class='padding5' style="display:block"><B>b3_1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row24_2' class='padding5' style="display:block">Flexibilidad (adaptabilidad al cambio)</div><INPUT type='hidden' name='objVals31row24_' id='objVals31row24_' value='0' lang='Por favor responder la pregunta b3_1' title='b3_1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row24_3' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='01' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_4' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='02' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_5' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='03' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_6' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='04' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_7' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='05' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_8' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='06' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_9' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='07' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_10' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='08' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_11' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='09' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_12' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='10' onClick="marcarSeleccion('objVals31row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row24_13' class='padding5' style="display:block"><INPUT type='radio' name='b3_1' id='b3_1' lang='' value='99' onClick="marcarSeleccion('objVals31row24_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s31row26_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s31row26_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row26_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row27_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row27_2' class='padding5' style="display:block">Calidad general del servicio ofrecido por GNN / DFA (Proceso de Nuevos Negocios de E&P)</div><INPUT type='hidden' name='objVals31row27_' id='objVals31row27_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals31row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals31row27_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s31row28_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s31row28_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s31row28_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row29_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row29_2' class='padding5' style="display:block">Manejo de las relaciones con las personas </div><INPUT type='hidden' name='objVals31row29_' id='objVals31row29_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals31row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals31row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row30_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row30_2' class='padding5' style="display:block">Conocimiento y experiencia del Equipo de Nuevos Negocios</div><INPUT type='hidden' name='objVals31row30_' id='objVals31row30_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals31row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals31row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row31_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row31_2' class='padding5' style="display:block">Claridad y efectividad en la comunicación </div><INPUT type='hidden' name='objVals31row31_' id='objVals31row31_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals31row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals31row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row32_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row32_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals31row32_' id='objVals31row32_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals31row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals31row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row33_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row33_2' class='padding5' style="display:block">Robustez y Aseguramiento del proceso </div><INPUT type='hidden' name='objVals31row33_' id='objVals31row33_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row33_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals31row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row33_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals31row33_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row34_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row34_2' class='padding5' style="display:block">Proactividad en la Gestión de Negocios</div><INPUT type='hidden' name='objVals31row34_' id='objVals31row34_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row34_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals31row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row34_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals31row34_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row35_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row35_2' class='padding5' style="display:block">Nivel de profundidad de los análisis </div><INPUT type='hidden' name='objVals31row35_' id='objVals31row35_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row35_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals31row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row35_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals31row35_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row36_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row36_2' class='padding5' style="display:block">Calidad de las presentaciones de las Oportunidades de Negocio</div><INPUT type='hidden' name='objVals31row36_' id='objVals31row36_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row36_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals31row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row36_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals31row36_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row37_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row37_2' class='padding5' style="display:block">Aporte a la generación de Valor del Grupo Empresarial</div><INPUT type='hidden' name='objVals31row37_' id='objVals31row37_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s31row37_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals31row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s31row37_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals31row37_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row39_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row39_2' class='padding5'>Usted diría que su relación con Nuevos Negocios…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s31row39_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s31row41_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s31row41_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante del Proceso de Nuevos Negocios de E&P?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s31row42_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s31row42_3' class='padding5' style="display:block">¿Qué se está haciendo bien en el Proceso de Nuevos Negocios de E&P?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s31row43_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s31row43_3' class='padding5' style="display:block">¿Qué se debe mejorar en el Proceso de Nuevos Negocios de E&P?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s31row45_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s31row45_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s31row45_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s31row45_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row46_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s31row46_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals31row46_' id='objVals31row46_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s31row46_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals31row46_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s31row46_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals31row46_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>