<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s9row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s9row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL UNIDAD</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s9row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s9row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row6_1' class='padding5' style="display:block"><B>1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row6_2' class='padding5' style="display:block">Cómo califica la calidad general de los SERVICIOS COMPARTIDOS DE COMPRAS y CONTRATACIÓN</div><INPUT type='hidden' name='objVals9row6_' id='objVals9row6_' value='0' lang='Por favor responder la pregunta 1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals9row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row8_1' class='padding5'><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row8_2' class='padding5'>Sabe usted como comunicarse con el Centro de Servicios Compartidos dado que tenga una observación o una solicitud específica sobre el servicio de Gestión Administrativa de Contratos?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s9row8_3' class='padding5'>
				<SELECT name='a11' id='a11' lang='1' title='Por favor responder la pregunta a11' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s9row9_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s9row9_2' class='padding5'>En general su relación con el Centro de Servicios compartidos en relación al servicio de Gestión Administrativa de Contratos es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s9row10_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj10' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s9row15_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s9row10_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s9row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s9row16_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s9row11_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s9row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s9row17_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s9row12_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s9row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='40' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s9row18_','a2d');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s9row13_2' class='padding2'>Portal/internet </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s9row14_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s9row14_2' class='padding5'>Teniendo en cuenta la atención brindada por el servicio de Gestión Administrativa de Contratos, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row14_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row15_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row15_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals9row15_' id='objVals9row15_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row15_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals9row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row15_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals9row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row16_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row16_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals9row16_' id='objVals9row16_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals9row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals9row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row17_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals9row17_' id='objVals9row17_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals9row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals9row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row18_1' class='padding5' style="display:none"><B>d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row18_2' class='padding5' style="display:none">¿Cómo califica el portal de Internet?</div><INPUT type='hidden' name='objVals9row18_' id='objVals9row18_' value='1' lang='Por favor responder la pregunta d' title='a2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row18_3' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='01' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_4' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='02' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_5' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='03' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_6' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='04' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_7' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='05' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_8' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='06' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_9' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='07' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_10' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='08' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_11' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='09' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_12' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='10' onClick="marcarSeleccion('objVals9row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row18_13' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='99' onClick="marcarSeleccion('objVals9row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s9row19_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s9row19_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en relación al servicio de Gestión Administrativa de Contratos? ¿Qué le gustaría ver? O Qué está haciendo falta?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s9row20_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s9row20_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row20_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row21_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row21_2' class='padding5' style="display:block">Los procesos de Gestión Integral de Contratos, el alcance del Servicio de Gestoría Administrativa de Contratos y los acuerdos de nivel de servicios?</div><INPUT type='hidden' name='objVals9row21_' id='objVals9row21_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row21_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals9row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row21_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals9row21_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row22_1' class='padding5' style="display:block"><B>a4_1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row22_2' class='padding5' style="display:block">El modelo  Gestión Integral de Contratos?</div><INPUT type='hidden' name='objVals9row22_' id='objVals9row22_' value='0' lang='Por favor responder la pregunta a4_1' title='a4_1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row22_3' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='01' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_4' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='02' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_5' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='03' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_6' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='04' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_7' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='05' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_8' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='06' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_9' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='07' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_10' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='08' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_11' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='09' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_12' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='10' onClick="marcarSeleccion('objVals9row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row22_13' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='99' onClick="marcarSeleccion('objVals9row22_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row23_1' class='padding5' style="display:block"><B>a4_2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row23_2' class='padding5' style="display:block">Los roles y responsabilidades que usted desempeña en el proceso?</div><INPUT type='hidden' name='objVals9row23_' id='objVals9row23_' value='0' lang='Por favor responder la pregunta a4_2' title='a4_2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row23_3' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='01' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_4' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='02' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_5' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='03' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_6' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='04' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_7' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='05' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_8' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='06' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_9' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='07' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_10' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='08' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_11' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='09' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_12' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='10' onClick="marcarSeleccion('objVals9row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row23_13' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='99' onClick="marcarSeleccion('objVals9row23_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s9row25_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s9row25_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row25_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row26_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row26_2' class='padding5' style="display:block">Calidad general del servicio de Gestión Administrativa de Contratos</div><INPUT type='hidden' name='objVals9row26_' id='objVals9row26_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals9row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals9row26_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s9row27_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s9row27_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s9row27_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row28_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row28_2' class='padding5' style="display:block">Amabilidad y comunicaciones de las personas</div><INPUT type='hidden' name='objVals9row28_' id='objVals9row28_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals9row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals9row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row29_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row29_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals9row29_' id='objVals9row29_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals9row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals9row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row30_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row30_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals9row30_' id='objVals9row30_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals9row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals9row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row31_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row31_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos establecidos en cada rol de la Gestión administrativa de contratos.</div><INPUT type='hidden' name='objVals9row31_' id='objVals9row31_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals9row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals9row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row32_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row32_2' class='padding5' style="display:block">Herramientas utilizadas tecnológicas , métodos , mejores prácticas, etc..</div><INPUT type='hidden' name='objVals9row32_' id='objVals9row32_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals9row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals9row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row33_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row33_2' class='padding5' style="display:block">El desempeño de los gestores financieros durante la ejecución del contrato</div><INPUT type='hidden' name='objVals9row33_' id='objVals9row33_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row33_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals9row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row33_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals9row33_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row34_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row34_2' class='padding5' style="display:block">El desempeño de los gestores laborales durante la ejecución del contrato</div><INPUT type='hidden' name='objVals9row34_' id='objVals9row34_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row34_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals9row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row34_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals9row34_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row35_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row35_2' class='padding5' style="display:block">El desempeño de los gestores HSE y Documentales durante la ejecución del contrato</div><INPUT type='hidden' name='objVals9row35_' id='objVals9row35_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row35_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals9row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row35_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals9row35_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row36_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row36_2' class='padding5' style="display:block">La calidad de la información sobre el estado de los contratos </div><INPUT type='hidden' name='objVals9row36_' id='objVals9row36_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s9row36_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals9row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s9row36_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals9row36_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row38_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row38_2' class='padding5'>Usted diría que su relación con el Centro de Servicios Compartidos…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s9row38_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row39_1' class='padding5'><B>c2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row39_2' class='padding5'>Y específicamente usted diría que el servicio de Gestión Administrativa de Contratos…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s9row39_3' class='padding5'>
				<SELECT name='c2' id='c2' lang='1' title='Por favor responder la pregunta c2' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s9row41_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s9row41_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante del servicio de Gestión Administrativa de Contratos?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s9row42_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s9row42_3' class='padding5' style="display:block">¿Qué  se está haciendo bien en el servicio de Gestión Administrativa de Contratos?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s9row43_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s9row43_3' class='padding5' style="display:block">¿Qué se debe mejorar en el servicio de Gestión Administrativa de Contratos?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row45_1' class='padding5'><B>&nbsp;</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s9row45_2' class='padding5'>Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s9row45_3' class='padding5'>
				<SELECT name='autoriza' id='autoriza' lang='1' title='Por favor responder la pregunta ' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>