<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s32row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s32row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s32row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s32row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row6_2' class='padding5' style="display:block">Cómo califica la calidad general de la GTT</div><INPUT type='hidden' name='objVals32row6_' id='objVals32row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals32row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s32row8_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s32row8_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s32row8_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s32row8_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row9_1' class='padding5' style="display:block"><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row9_2' class='padding5' style="display:block">Sabe usted como comunicase con GTT dado que tenga una observación o una solicitud específica sobre el servicio que recibe?</div><INPUT type='hidden' name='objVals32row9_' id='objVals32row9_' value='0' lang='Por favor responder la pregunta a11' title='a11'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s32row9_3' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='1' onClick="marcarSeleccion('objVals32row9_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s32row9_4' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='2' onClick="marcarSeleccion('objVals32row9_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s32row10_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s32row10_2' class='padding5'>En general su relación con las personas del GTT es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s32row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s32row16_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s32row11_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s32row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s32row17_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s32row12_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s32row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s32row18_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s32row13_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s32row14_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj14' value='40' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s32row19_','a2d');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s32row14_2' class='padding2'>Tecnical query (es un formato de consultas técnicas) </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s32row15_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s32row15_2' class='padding5'>Teniendo en cuenta la atención brindada por GTT, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row15_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row16_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row16_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals32row16_' id='objVals32row16_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals32row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals32row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row17_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals32row17_' id='objVals32row17_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals32row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals32row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row18_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row18_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals32row18_' id='objVals32row18_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row18_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals32row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row18_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals32row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row19_1' class='padding5' style="display:none"><B>d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row19_2' class='padding5' style="display:none">Tecnical query (es un formato de consultas técnicas)</div><INPUT type='hidden' name='objVals32row19_' id='objVals32row19_' value='1' lang='Por favor responder la pregunta d' title='a2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row19_3' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='01' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_4' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='02' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_5' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='03' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_6' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='04' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_7' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='05' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_8' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='06' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_9' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='07' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_10' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='08' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_11' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='09' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_12' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='10' onClick="marcarSeleccion('objVals32row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row19_13' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='99' onClick="marcarSeleccion('objVals32row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s32row20_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s32row20_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en la GTT? Qué le gustaría ver? O Qué está haciendo falta para lograr sus objetivos o el cumplimiento de sus acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s32row21_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s32row21_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row21_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row22_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row22_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los procesos, acuerdos de nivel de servicios o en general a la GTT?</div><INPUT type='hidden' name='objVals32row22_' id='objVals32row22_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row22_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals32row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row22_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals32row22_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s32row24_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s32row24_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row24_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row25_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row25_2' class='padding5' style="display:block">Calidad general de los procesos de la GTT</div><INPUT type='hidden' name='objVals32row25_' id='objVals32row25_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals32row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals32row25_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s32row26_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s32row26_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row26_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row27_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row27_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals32row27_' id='objVals32row27_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals32row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals32row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row28_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row28_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals32row28_' id='objVals32row28_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals32row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals32row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row29_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row29_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals32row29_' id='objVals32row29_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals32row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals32row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row30_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row30_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals32row30_' id='objVals32row30_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals32row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals32row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row31_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row31_2' class='padding5' style="display:block">Herramientas utilizadas tecnológicas o de métodos y otras herramientas </div><INPUT type='hidden' name='objVals32row31_' id='objVals32row31_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals32row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals32row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row32_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row32_2' class='padding5' style="display:block">Acompañamiento, seguimiento y soporte </div><INPUT type='hidden' name='objVals32row32_' id='objVals32row32_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals32row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals32row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row33_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row33_2' class='padding5' style="display:block">Estructuración y optimización </div><INPUT type='hidden' name='objVals32row33_' id='objVals32row33_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row33_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals32row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row33_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals32row33_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row34_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row34_2' class='padding5' style="display:block">Reglamentaciones técnicas realizadas</div><INPUT type='hidden' name='objVals32row34_' id='objVals32row34_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row34_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals32row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row34_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals32row34_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row35_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row35_2' class='padding5' style="display:block">Gestion del aseguramiento y direccionamiento</div><INPUT type='hidden' name='objVals32row35_' id='objVals32row35_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row35_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals32row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row35_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals32row35_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s32row36_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s32row36_2' class='padding5'>Más específicamente en la gestión del aseguramiento y direccionamiento de:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s32row36_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row37_1' class='padding5' style="display:block"><B>b10a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row37_2' class='padding5' style="display:block">Conocimiento (para el mejoramiento del capital humano)</div><INPUT type='hidden' name='objVals32row37_' id='objVals32row37_' value='0' lang='Por favor responder la pregunta b10a' title='b10a_f2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row37_3' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='01' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_4' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='02' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_5' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='03' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_6' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='04' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_7' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='05' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_8' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='06' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_9' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='07' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_10' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='08' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_11' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='09' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_12' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='10' onClick="marcarSeleccion('objVals32row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row37_13' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='99' onClick="marcarSeleccion('objVals32row37_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row38_1' class='padding5' style="display:block"><B>b10b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row38_2' class='padding5' style="display:block">Tecnología del negocio</div><INPUT type='hidden' name='objVals32row38_' id='objVals32row38_' value='0' lang='Por favor responder la pregunta b10b' title='b10b_f2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row38_3' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='01' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_4' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='02' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_5' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='03' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_6' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='04' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_7' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='05' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_8' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='06' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_9' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='07' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_10' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='08' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_11' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='09' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_12' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='10' onClick="marcarSeleccion('objVals32row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row38_13' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='99' onClick="marcarSeleccion('objVals32row38_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row39_1' class='padding5' style="display:block"><B>b10c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row39_2' class='padding5' style="display:block">Información técnica de las proyectos y procesos</div><INPUT type='hidden' name='objVals32row39_' id='objVals32row39_' value='0' lang='Por favor responder la pregunta b10c' title='b10c_f2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s32row39_3' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='01' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_4' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='02' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_5' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='03' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_6' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='04' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_7' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='05' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_8' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='06' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_9' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='07' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_10' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='08' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_11' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='09' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_12' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='10' onClick="marcarSeleccion('objVals32row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s32row39_13' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='99' onClick="marcarSeleccion('objVals32row39_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row41_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row41_2' class='padding5'>Usted diría que su relación con la GTT…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s32row41_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s32row43_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s32row43_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante de la GTT?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s32row44_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s32row44_3' class='padding5' style="display:block">¿Qué se está haciendo bien la GTT?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s32row45_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s32row45_3' class='padding5' style="display:block">¿Qué se debe mejorar en la GTT?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s32row47_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s32row47_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s32row47_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s32row47_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row48_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s32row48_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals32row48_' id='objVals32row48_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s32row48_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals32row48_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s32row48_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals32row48_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>