<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s19row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s19row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL UNIDAD</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s19row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s19row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row6_1' class='padding5' style="display:block"><B>1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row6_2' class='padding5' style="display:block">Cómo califica la calidad general de los SERVICIOS COMPARTIDOS DE PERSONAL</div><INPUT type='hidden' name='objVals19row6_' id='objVals19row6_' value='0' lang='Por favor responder la pregunta 1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals19row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s19row8_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s19row8_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row8_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row9_1' class='padding5' style="display:block"><B>a2d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row9_2' class='padding5' style="display:block">¿Cómo califica la calidad general del Empleo.com para tramitar su solicitud a ECOPETROL?</div><INPUT type='hidden' name='objVals19row9_' id='objVals19row9_' value='0' lang='Por favor responder la pregunta a2d' title='a2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row9_3' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='01' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_4' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='02' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_5' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='03' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_6' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='04' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_7' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='05' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_8' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='06' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_9' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='07' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_10' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='08' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_11' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='09' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_12' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='10' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row9_13' class='padding5' style="display:block"><INPUT type='radio' name='a2d' id='a2d' lang='' value='99' onClick=" marcarSeleccion('objVals19row9_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s19row10_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s19row10_3' class='padding5' style="display:block">¿Qué espera y no encuentra en el proceso de Selección de personal de Ecopetrol? ¿Qué le gustaría ver? o qué está haciendo falta para lograr los objetivos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s19row11_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s19row11_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row11_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row12_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row12_2' class='padding5' style="display:block">¿Qué tanto diría usted que le dieron a conocer el proceso y los tiempos de selección de personal?</div><INPUT type='hidden' name='objVals19row12_' id='objVals19row12_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row12_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals19row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row12_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals19row12_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s19row14_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s19row14_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row14_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row15_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row15_2' class='padding5' style="display:block">Calidad general del Servicio de Selección</div><INPUT type='hidden' name='objVals19row15_' id='objVals19row15_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row15_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals19row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row15_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals19row15_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s19row16_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s19row16_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s19row16_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row17_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row17_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals19row17_' id='objVals19row17_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row17_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals19row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row17_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals19row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row18_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row18_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals19row18_' id='objVals19row18_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row18_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals19row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row18_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals19row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row19_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row19_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals19row19_' id='objVals19row19_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row19_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals19row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row19_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals19row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row20_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row20_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals19row20_' id='objVals19row20_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row20_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals19row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row20_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals19row20_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row21_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row21_2' class='padding5' style="display:block">Herramientas utilizadas tecnológicas o de métodos e instalaciones </div><INPUT type='hidden' name='objVals19row21_' id='objVals19row21_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row21_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals19row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row21_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals19row21_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row22_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row22_2' class='padding5' style="display:block">La información brindada con respecto a los requerimientos de la documentación para su vinculación (claridad, información completa)</div><INPUT type='hidden' name='objVals19row22_' id='objVals19row22_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row22_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals19row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row22_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals19row22_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row23_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row23_2' class='padding5' style="display:block">El tiempo dado para la obtención de los documentos necesarios para el ingreso</div><INPUT type='hidden' name='objVals19row23_' id='objVals19row23_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row23_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals19row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row23_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals19row23_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row24_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row24_2' class='padding5' style="display:block">La puntualidad del desarrollo de las pruebas técnicas, entrevistas y demás actividades</div><INPUT type='hidden' name='objVals19row24_' id='objVals19row24_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row24_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals19row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row24_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals19row24_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row25_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row25_2' class='padding5' style="display:block">Atención prestada a sus inquietudes y dudas.</div><INPUT type='hidden' name='objVals19row25_' id='objVals19row25_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s19row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals19row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s19row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals19row25_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row26_1' class='padding5'><B>b11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row26_2' class='padding5'>Contó con los canales apropiados para la solución de dudas sobre los trámites de documentación requerida para su vinculación?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s19row26_3' class='padding5'>
				<SELECT name='b11' id='b11' lang='1' title='Por favor responder la pregunta b11' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row28_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row28_2' class='padding5'>Usted diría que su relación con el Centro de Servicios Compartidos…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s19row28_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row29_1' class='padding5'><B>c2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row29_2' class='padding5'>Y específicamente usted diría que el servicio de selección de ECOPETROL…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s19row29_3' class='padding5'>
				<SELECT name='c2' id='c2' lang='1' title='Por favor responder la pregunta c2' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s19row31_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s19row31_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante del servicio de selección de personal de ECOPETROL?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s19row32_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s19row32_3' class='padding5' style="display:block">¿Qué se está haciendo bien en el servicio de selección de personal de ECOPETROL?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s19row33_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s19row33_3' class='padding5' style="display:block">¿Qué se debe mejorar en el servicio de selección de personal de ECOPETROL?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s19row34_1' class='padding5' style="display:block"><B>d4.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s19row34_3' class='padding5' style="display:block">(Solo para candidatos) Qué hizo falta para que el proceso de selección hubiera sido exitoso con ECOPETROL? O Cuál es su visión del proceso para que éste sea ideal?<BR /><TEXTAREA name='vb_d4' id='vb_d4' lang='1' title='Por favor responder la pregunta d4' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row36_1' class='padding5'><B>&nbsp;</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s19row36_2' class='padding5'>Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s19row36_3' class='padding5'>
				<SELECT name='autoriza' id='autoriza' lang='1' title='Por favor responder la pregunta ' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>