<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s2row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s2row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL UNIDAD</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s2row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s2row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row6_2' class='padding5' style="display:block">Cómo califica la calidad general de los SERVICIOS COMPARTIDOS INMOBILIARIOS y ADMINISTRATIVOS</div><INPUT type='hidden' name='objVals2row6_' id='objVals2row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals2row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row8_1' class='padding5'><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row8_2' class='padding5'>Sabe usted como comunicase con el Centro de Servicios Compartidos dado que tenga una observación o una solicitud específica sobre el servicio de Alimentación?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s2row8_3' class='padding5'>
				<SELECT name='a11' id='a11' lang='1' title='Por favor responder la pregunta a11' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s2row9_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s2row9_2' class='padding5'>En general su relación con el  Centro de Servicios Compartidos en relación al servicio de es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row10_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj10' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s2row16_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row10_2' class='padding2'>Teléfono Call Center del CSC </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s2row17_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row11_2' class='padding2'>Persona encargada de la cafetería o el servicio </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s2row18_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row12_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='50' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s2row19_','a2e');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row13_2' class='padding2'>Buzón de sugerencias </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row14_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj14' value='21' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s2row20_','a2b1');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row14_2' class='padding2'>Comité de usuarios </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s2row15_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s2row15_2' class='padding5'>Teniendo en cuenta la atención brindada por el servicio de alimentación, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row15_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row16_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row16_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals2row16_' id='objVals2row16_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals2row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals2row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row17_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de las personas encargada de la cafetería?</div><INPUT type='hidden' name='objVals2row17_' id='objVals2row17_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals2row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals2row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row18_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row18_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals2row18_' id='objVals2row18_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row18_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals2row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row18_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals2row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row19_1' class='padding5' style="display:none"><B>d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row19_2' class='padding5' style="display:none">¿Cómo califica el Buzón de sugerencias?</div><INPUT type='hidden' name='objVals2row19_' id='objVals2row19_' value='1' lang='Por favor responder la pregunta d' title='a2e'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row19_3' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='01' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_4' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='02' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_5' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='03' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_6' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='04' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_7' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='05' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_8' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='06' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_9' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='07' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_10' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='08' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_11' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='09' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_12' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='10' onClick="marcarSeleccion('objVals2row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row19_13' class='padding5' style="display:none"><INPUT type='radio' name='a2e' id='a2e' lang='' value='99' onClick="marcarSeleccion('objVals2row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row20_1' class='padding5' style="display:none"><B>e.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row20_2' class='padding5' style="display:none">¿Cómo califica el Comité de usuarios?</div><INPUT type='hidden' name='objVals2row20_' id='objVals2row20_' value='1' lang='Por favor responder la pregunta e' title='a2b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row20_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='01' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='02' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='03' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='04' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='05' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='06' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='07' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='08' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='09' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='10' onClick="marcarSeleccion('objVals2row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row20_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='99' onClick="marcarSeleccion('objVals2row20_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s2row21_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s2row21_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en el servicio de alimentación? ¿Qué le gustaría ver? O Qué está haciendo falta?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s2row22_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s2row22_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row22_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row23_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row23_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce el proceso de alimentación en términos de quién tiene derecho a los beneficios de alimentación?</div><INPUT type='hidden' name='objVals2row23_' id='objVals2row23_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row23_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals2row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row23_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals2row23_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s2row25_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s2row25_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row25_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row26_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row26_2' class='padding5' style="display:block">Calidad general del servicio de alimentación</div><INPUT type='hidden' name='objVals2row26_' id='objVals2row26_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals2row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals2row26_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s2row27_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s2row27_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row27_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row28_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row28_2' class='padding5' style="display:block">Amabilidad de las personas que lo atienden</div><INPUT type='hidden' name='objVals2row28_' id='objVals2row28_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals2row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals2row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row29_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row29_2' class='padding5' style="display:block">Experticia en el manejo de los alimentos y los restaurantes: higiene, presentación, etc.</div><INPUT type='hidden' name='objVals2row29_' id='objVals2row29_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals2row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals2row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row30_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row30_2' class='padding5' style="display:block">Claridad de la información sobre el servicio y las personas a contactar en caso de sugerencias</div><INPUT type='hidden' name='objVals2row30_' id='objVals2row30_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals2row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals2row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row31_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row31_2' class='padding5' style="display:block">Cumplimiento de los horarios atención y/o horas de entrega de alimentación</div><INPUT type='hidden' name='objVals2row31_' id='objVals2row31_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals2row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals2row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row32_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row32_2' class='padding5' style="display:block">Tecnología utilizada para el manejo de los tiquetes de alimentación </div><INPUT type='hidden' name='objVals2row32_' id='objVals2row32_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals2row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals2row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row33_1' class='padding5'><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row33_2' class='padding5'>Conoce el Programa Vida Sana?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s2row33_3' class='padding5'>
				<SELECT name='b7_f2' id='b7_f2' lang='1' title='Por favor responder la pregunta b7' class='userText' onchange="salto(this.id,this.value,'1','s2row34_,s2row35_,s2row36_,s2row37_,s2row38_,s2row39_,s2row40_,s2row41_,s2row42_,s2row43_,s2row44_,s2row45_,s2row46_,s2row47_','objVal_b8,idObj35,idObj36,idObj37,idObj38,b8_otro_f2,b9_f2,b10a_f2,b10b_f2,b10c_f2,b10d_f2,vb_b11_f2');">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s2row34_1' class='padding5'><B>b8.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s2row34_2' class='padding5'>A través de qué medio conoció el Programa Vida Sana?</div><INPUT type='hidden' name='objVal_b8' id='objVal_b8' value='0' lang='Por favor responder la pregunta b8'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row35_1' class='padding2'><INPUT type='checkbox' name='b8_f2[]' id='idObj35' value='10' lang='0' onClick="marcarSeleccion('objVal_b8'); " /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row35_2' class='padding2'>Letreros o información en carteleras </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row36_1' class='padding2'><INPUT type='checkbox' name='b8_f2[]' id='idObj36' value='20' lang='0' onClick="marcarSeleccion('objVal_b8'); " /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row36_2' class='padding2'>Persona encargada de la cafetería o el servicio </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row37_1' class='padding2'><INPUT type='checkbox' name='b8_f2[]' id='idObj37' value='30' lang='0' onClick="marcarSeleccion('objVal_b8'); " /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row37_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row38_1' class='padding2'><INPUT type='checkbox' name='b8_f2[]' id='idObj38' value='77' lang='0' onClick="marcarSeleccion('objVal_b8'); habilitarOtro(this.checked,'b8_otro_f2');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row38_2' class='padding2'>Otro, cuál? &nbsp;<INPUT type='text' name='b8_otro_f2' id='b8_otro_f2' class='borderBlue' value='' lang='1' style='width:300px; padding:3px 5px;' disabled='disabled' title='Ingrese una respuesta válida' /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row40_1' class='padding5'><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row40_2' class='padding5'>Utiliza o está inscrito en el Programa Vida Sana?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s2row40_3' class='padding5'>
				<SELECT name='b9_f2' id='b9_f2' lang='1' title='Por favor responder la pregunta b9' class='userText' onchange="salto(this.id,this.value,'1','s2row41_,s2row42_,s2row43_,s2row44_,s2row45_,s2row46_,s2row47_','b10a_f2,b10b_f2,b10c_f2,b10d_f2,vb_b11_f2');">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s2row41_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s2row41_2' class='padding5'>En una escala de 1 a 10 donde 1 es malo y 10 es excelente…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row41_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row42_1' class='padding5' style="display:block"><B>b10a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row42_2' class='padding5' style="display:block">¿Cómo califica en general al Programa Vida Sana?</div><INPUT type='hidden' name='objVals2row42_' id='objVals2row42_' value='0' lang='Por favor responder la pregunta b10a' title='b10a_f2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row42_3' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='01' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_4' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='02' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_5' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='03' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_6' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='04' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_7' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='05' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_8' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='06' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_9' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='07' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_10' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='08' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_11' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='09' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_12' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='10' onClick="marcarSeleccion('objVals2row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row42_13' class='padding5' style="display:block"><INPUT type='radio' name='b10a_f2' id='b10a_f2' lang='' value='99' onClick="marcarSeleccion('objVals2row42_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s2row43_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s2row43_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s2row43_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row44_1' class='padding5' style="display:block"><B>b10b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row44_2' class='padding5' style="display:block">Charlas de la nutricionistas</div><INPUT type='hidden' name='objVals2row44_' id='objVals2row44_' value='0' lang='Por favor responder la pregunta b10b' title='b10b_f2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row44_3' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='01' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_4' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='02' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_5' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='03' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_6' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='04' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_7' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='05' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_8' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='06' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_9' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='07' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_10' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='08' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_11' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='09' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_12' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='10' onClick="marcarSeleccion('objVals2row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row44_13' class='padding5' style="display:block"><INPUT type='radio' name='b10b_f2' id='b10b_f2' lang='' value='99' onClick="marcarSeleccion('objVals2row44_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row45_1' class='padding5' style="display:block"><B>b10c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row45_2' class='padding5' style="display:block">Calidad del menú alterno</div><INPUT type='hidden' name='objVals2row45_' id='objVals2row45_' value='0' lang='Por favor responder la pregunta b10c' title='b10c_f2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row45_3' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='01' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_4' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='02' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_5' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='03' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_6' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='04' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_7' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='05' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_8' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='06' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_9' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='07' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_10' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='08' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_11' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='09' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_12' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='10' onClick="marcarSeleccion('objVals2row45_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row45_13' class='padding5' style="display:block"><INPUT type='radio' name='b10c_f2' id='b10c_f2' lang='' value='99' onClick="marcarSeleccion('objVals2row45_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row46_1' class='padding5' style="display:block"><B>b10d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row46_2' class='padding5' style="display:block">Apoyarlo a cambiar sus hábitos </div><INPUT type='hidden' name='objVals2row46_' id='objVals2row46_' value='0' lang='Por favor responder la pregunta b10d' title='b10d_f2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s2row46_3' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='01' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_4' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='02' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_5' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='03' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_6' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='04' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_7' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='05' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_8' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='06' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_9' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='07' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_10' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='08' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_11' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='09' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_12' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='10' onClick="marcarSeleccion('objVals2row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s2row46_13' class='padding5' style="display:block"><INPUT type='radio' name='b10d_f2' id='b10d_f2' lang='' value='99' onClick="marcarSeleccion('objVals2row46_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s2row47_1' class='padding5' style="display:block"><B>b11.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s2row47_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en el Programa Vida Sana, ¿Qué le gustaría ver? O Qué está haciendo falta?<BR /><TEXTAREA name='vb_b11_f2' id='vb_b11_f2' lang='1' title='Por favor responder la pregunta b11' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row48_1' class='padding5'><B>b12.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row48_2' class='padding5'>Conoce o ha oído el programa del Plato Limpio?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s2row48_3' class='padding5'>
				<SELECT name='b12_f2' id='b12_f2' lang='1' title='Por favor responder la pregunta b12' class='userText' onchange="salto(this.id,this.value,'1','s2row49_,s2row50_,s2row51_,s2row52_,s2row53_','objVal_b13,idObj50,idObj51,idObj52,idObj53,b13_otro_f2');">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s2row49_1' class='padding5'><B>b13.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s2row49_2' class='padding5'>A través de qué medio conoció el programa del Plato Limpio?</div><INPUT type='hidden' name='objVal_b13' id='objVal_b13' value='0' lang='Por favor responder la pregunta b13'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row50_1' class='padding2'><INPUT type='checkbox' name='b13_f2[]' id='idObj50' value='10' lang='0' onClick="marcarSeleccion('objVal_b13'); " /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row50_2' class='padding2'>Letreros o información en carteleras </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row51_1' class='padding2'><INPUT type='checkbox' name='b13_f2[]' id='idObj51' value='20' lang='0' onClick="marcarSeleccion('objVal_b13'); " /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row51_2' class='padding2'>Persona encargada de la cafetería o el servicio </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row52_1' class='padding2'><INPUT type='checkbox' name='b13_f2[]' id='idObj52' value='30' lang='0' onClick="marcarSeleccion('objVal_b13'); " /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row52_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s2row53_1' class='padding2'><INPUT type='checkbox' name='b13_f2[]' id='idObj53' value='77' lang='0' onClick="marcarSeleccion('objVal_b13'); habilitarOtro(this.checked,'b13_otro_f2');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s2row53_2' class='padding2'>Otro, cuál? &nbsp;<INPUT type='text' name='b13_otro_f2' id='b13_otro_f2' class='borderBlue' value='' lang='1' style='width:300px; padding:3px 5px;' disabled='disabled' title='Ingrese una respuesta válida' /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row55_1' class='padding5'><B>b14.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row55_2' class='padding5'>Participa o le gustaría participar en el programa plato limpio que consiste en obtener premios por comerse todo lo que se sirvió?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s2row55_3' class='padding5'>
				<SELECT name='b14_f2' id='b14_f2' lang='1' title='Por favor responder la pregunta b14' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row57_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row57_2' class='padding5'>Usted diría que su relación con el Centro de Servicios Compartidos…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s2row57_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row58_1' class='padding5'><B>c2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row58_2' class='padding5'>Y específicamente usted diría que el servicio de Alimentación…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s2row58_3' class='padding5'>
				<SELECT name='c2' id='c2' lang='1' title='Por favor responder la pregunta c2' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s2row60_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s2row60_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante del Servicio de Alimentación?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s2row61_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s2row61_3' class='padding5' style="display:block">¿Qué se está haciendo bien en el Servicio de Alimentación?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s2row62_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s2row62_3' class='padding5' style="display:block">¿Qué se debe mejorar en el Servicio de Alimentación?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row64_1' class='padding5'><B>&nbsp;</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s2row64_2' class='padding5'>Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s2row64_3' class='padding5'>
				<SELECT name='autoriza' id='autoriza' lang='1' title='Por favor responder la pregunta ' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>