<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s45row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s45row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s45row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s45row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row6_2' class='padding5' style="display:block">Cómo califica la calidad general a la DHS – Dirección de HSE</div><INPUT type='hidden' name='objVals45row6_' id='objVals45row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals45row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s45row8_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s45row8_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s45row8_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s45row8_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row9_1' class='padding5' style="display:block"><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row9_2' class='padding5' style="display:block">Sabe usted como comunicase con DHS dado que tenga una observación o una solicitud específica sobre los temas que le competen?</div><INPUT type='hidden' name='objVals45row9_' id='objVals45row9_' value='0' lang='Por favor responder la pregunta a11' title='a11'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s45row9_3' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='1' onClick="marcarSeleccion('objVals45row9_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s45row9_4' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='2' onClick="marcarSeleccion('objVals45row9_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s45row10_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s45row10_2' class='padding5'>En general su relación con las personas de DHS es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s45row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s45row15_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s45row11_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s45row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s45row16_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s45row12_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s45row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s45row17_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s45row13_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s45row14_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s45row14_2' class='padding5'>Teniendo en cuenta la atención brindada, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row14_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row15_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row15_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals45row15_' id='objVals45row15_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row15_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals45row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row15_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals45row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row16_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row16_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals45row16_' id='objVals45row16_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals45row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals45row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row17_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals45row17_' id='objVals45row17_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals45row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals45row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s45row18_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s45row18_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en DHS? Qué le gustaría ver? O Qué está haciendo falta para lograr sus objetivos o el cumplimiento de sus acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s45row19_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s45row19_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row19_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row20_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row20_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los procesos, en general de DHS?</div><INPUT type='hidden' name='objVals45row20_' id='objVals45row20_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row20_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals45row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row20_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals45row20_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s45row22_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s45row22_2' class='padding5'>En relación con los procesos de DHS, en una escala de 1 a 10 donde 1 es malo y 10 excelente…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row22_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row23_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row23_2' class='padding5' style="display:block">Calidad general de los procesos de DHS</div><INPUT type='hidden' name='objVals45row23_' id='objVals45row23_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row23_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals45row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row23_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals45row23_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s45row24_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s45row24_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s45row24_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row25_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row25_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals45row25_' id='objVals45row25_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals45row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals45row25_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row26_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row26_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals45row26_' id='objVals45row26_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals45row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals45row26_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row27_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row27_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals45row27_' id='objVals45row27_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals45row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals45row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row28_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row28_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals45row28_' id='objVals45row28_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals45row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals45row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row29_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row29_2' class='padding5' style="display:block">Herramientas utilizadas tecnológicas o de métodos y otras herramientas </div><INPUT type='hidden' name='objVals45row29_' id='objVals45row29_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals45row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals45row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row30_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row30_2' class='padding5' style="display:block">La gestión de la estrategia ambiental formulada para Ecopetrol</div><INPUT type='hidden' name='objVals45row30_' id='objVals45row30_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals45row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals45row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row31_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row31_2' class='padding5' style="display:block">La asistencia técnica para apoyar la gestión y el cumplimiento de los objetivos de DHS </div><INPUT type='hidden' name='objVals45row31_' id='objVals45row31_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals45row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals45row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row32_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row32_2' class='padding5' style="display:block">Las directrices, guías, procedimientos de seguridad industrial, seguridad de procesos, gestión ambiental, salud ocupacional emitidos porDHS</div><INPUT type='hidden' name='objVals45row32_' id='objVals45row32_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s45row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals45row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s45row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals45row32_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row34_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row34_2' class='padding5'>Usted diría que su relación con el DHS …</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s45row34_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s45row36_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s45row36_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante de la DHS?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s45row37_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s45row37_3' class='padding5' style="display:block">Qué se está haciendo bien en DHS?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s45row38_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s45row38_3' class='padding5' style="display:block">¿Qué se debe mejorar en DHS?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s45row40_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s45row40_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s45row40_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s45row40_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row41_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s45row41_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals45row41_' id='objVals45row41_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s45row41_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals45row41_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s45row41_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals45row41_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>