<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s20row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s20row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL UNIDAD</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s20row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s20row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row6_2' class='padding5' style="display:block">Cómo califica la calidad general de los SERVICIOS COMPARTIDOS DE TECNOLOGÍA DE INFORMACIÓN</div><INPUT type='hidden' name='objVals20row6_' id='objVals20row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals20row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row8_1' class='padding5'><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row8_2' class='padding5'>Sabe usted como comunicarse con el Centro de Servicios Compartidos dado que tenga una observación o una solicitud específica sobre el servicio de <u>Habilitar Servicios Básicos de usuario Final?</u></div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s20row8_3' class='padding5'>
				<SELECT name='a11' id='a11' lang='1' title='Por favor responder la pregunta a11' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s20row9_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s20row9_2' class='padding5'>En general su relación con el  Centro de Servicios Compartidos en relación al servicio de <u>Habilitar Servicios básicos de usuario Final</u> es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s20row10_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj10' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s20row15_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s20row10_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s20row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s20row16_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s20row11_2' class='padding2'>Presencial soporte en sitio </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s20row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s20row17_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s20row12_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s20row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='40' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s20row18_','a2d');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s20row13_2' class='padding2'>Portal/internet - Service Manager </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s20row14_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s20row14_2' class='padding5'>Teniendo en cuenta la atención brindada por <u>Habilitar Servicios Básicos de TI para usuario Final</u>, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row14_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row15_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row15_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals20row15_' id='objVals20row15_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row15_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals20row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row15_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals20row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row16_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row16_2' class='padding5' style="display:none">¿Cómo califica la calidad del soporte en sitio presencial?</div><INPUT type='hidden' name='objVals20row16_' id='objVals20row16_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals20row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals20row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row17_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de la atención a través del correo electrónico?</div><INPUT type='hidden' name='objVals20row17_' id='objVals20row17_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals20row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals20row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row18_1' class='padding5' style="display:none"><B>d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row18_2' class='padding5' style="display:none">¿Cómo califica el portal de servicios compartidos - Service Manager?</div><INPUT type='hidden' name='objVals20row18_' id='objVals20row18_' value='1' lang='Por favor responder la pregunta d' title='a2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row18_3' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='01' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_4' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='02' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_5' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='03' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_6' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='04' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_7' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='05' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_8' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='06' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_9' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='07' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_10' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='08' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_11' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='09' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_12' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='10' onClick="marcarSeleccion('objVals20row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row18_13' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='99' onClick="marcarSeleccion('objVals20row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s20row19_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s20row19_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en relación al servicio de <u>Habilitar Servicios Basicos de TI para usuario Final?</u>  ¿Qué le gustaría ver? O Qué está haciendo falta para lograr los objetivos o el cumplimiento de los acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s20row20_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s20row20_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row20_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row21_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row21_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los tiempos en que será atendido su requerimiento?</div><INPUT type='hidden' name='objVals20row21_' id='objVals20row21_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row21_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals20row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row21_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals20row21_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s20row23_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s20row23_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row23_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row24_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row24_2' class='padding5' style="display:block">Calidad general del servicio de <u>Habilitar  Servicios Basicos de TI para usuario Final</u></div><INPUT type='hidden' name='objVals20row24_' id='objVals20row24_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row24_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals20row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row24_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals20row24_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s20row25_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s20row25_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s20row25_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row26_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row26_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals20row26_' id='objVals20row26_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals20row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals20row26_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row27_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row27_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals20row27_' id='objVals20row27_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals20row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals20row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row28_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row28_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals20row28_' id='objVals20row28_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals20row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals20row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row29_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row29_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals20row29_' id='objVals20row29_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals20row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals20row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row30_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row30_2' class='padding5' style="display:block">Herramientas utilizadas tecnológicas, métodos y mejores prácticas</div><INPUT type='hidden' name='objVals20row30_' id='objVals20row30_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals20row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals20row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row31_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row31_2' class='padding5' style="display:block">Califique la atención brindada de la mesa de servicio en horarios no hábiles</div><INPUT type='hidden' name='objVals20row31_' id='objVals20row31_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s20row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals20row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s20row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals20row31_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row33_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row33_2' class='padding5'>Usted diría que su relación con el Centro de Servicios Compartidos…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s20row33_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row34_1' class='padding5'><B>c2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row34_2' class='padding5'>Y específicamente usted diría que el servicio de <u>Habilitar Servicios básicos de TI para usuario Final…</u></div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s20row34_3' class='padding5'>
				<SELECT name='c2' id='c2' lang='1' title='Por favor responder la pregunta c2' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s20row36_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s20row36_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante del servicio de <u>Habilitar Servicios Básicos de TI para usuario Final?</u><BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s20row37_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s20row37_3' class='padding5' style="display:block">¿Qué se está haciendo bien en el servicio de <u>Habilitar Servicios Básicos de TI para usuario Final?</u><BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s20row38_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s20row38_3' class='padding5' style="display:block">¿Qué se debe mejorar en el servicio de <u>Habilitar Servicios Basicos de TI para usuario Final?</u><BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row40_1' class='padding5'><B>&nbsp;</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s20row40_2' class='padding5'>Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s20row40_3' class='padding5'>
				<SELECT name='autoriza' id='autoriza' lang='1' title='Por favor responder la pregunta ' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>SI</OPTION><OPTION value='2'>NO</OPTION>
				</SELECT></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>