<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s33row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s33row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s33row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s33row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row6_2' class='padding5' style="display:block">Cómo califica la calidad general del servicio de proyectos de la SPY-GTT</div><INPUT type='hidden' name='objVals33row6_' id='objVals33row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals33row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s33row8_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s33row8_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s33row8_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s33row8_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row9_1' class='padding5' style="display:block"><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row9_2' class='padding5' style="display:block">Sabe usted como comunicarse con el área de proyectos de GTT si tiene una observación o una solicitud específica sobre el servicio que recibe de ejecución de proyectos?</div><INPUT type='hidden' name='objVals33row9_' id='objVals33row9_' value='0' lang='Por favor responder la pregunta a11' title='a11'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s33row9_3' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='1' onClick="marcarSeleccion('objVals33row9_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s33row9_4' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='2' onClick="marcarSeleccion('objVals33row9_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s33row10_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s33row10_2' class='padding5'>En general su relación con las personas que ejecutan los proyectos de la GTT es a través de:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s33row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s33row19_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s33row11_2' class='padding2'>Teléfono </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s33row12_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s33row12_2' class='padding5'>Reuniones o de forma presencial con:</div></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s33row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='21' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s33row20_','a2b1');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s33row13_2' class='padding2'>* Coordinadores de estación </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s33row14_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj14' value='22' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s33row21_','a2b2');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s33row14_2' class='padding2'>* Profesionales y técnicos </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s33row15_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj15' value='23' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s33row22_','a2b3');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s33row15_2' class='padding2'>* Visitas en campo </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s33row16_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj16' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s33row23_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s33row16_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s33row17_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj17' value='40' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s33row24_','a2d');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s33row17_2' class='padding2'>Portal/Internet </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s33row18_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s33row18_2' class='padding5'>Teniendo en cuenta la atención brindada por los equipos de proyectos de la SPY-GTT, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row18_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row19_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row19_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals33row19_' id='objVals33row19_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row19_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals33row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row19_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals33row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row20_1' class='padding5' style="display:none"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row20_2' class='padding5' style="display:none">¿Cómo califica la calidad de los Líderes de Proyectos?</div><INPUT type='hidden' name='objVals33row20_' id='objVals33row20_' value='1' lang='Por favor responder la pregunta b1' title='a2b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row20_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='01' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='02' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='03' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='04' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='05' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='06' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='07' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='08' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='09' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='10' onClick="marcarSeleccion('objVals33row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row20_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='99' onClick="marcarSeleccion('objVals33row20_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row21_1' class='padding5' style="display:none"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row21_2' class='padding5' style="display:none">¿Cómo califica la calidad de los Profesionales y técnicos de proyectos?</div><INPUT type='hidden' name='objVals33row21_' id='objVals33row21_' value='1' lang='Por favor responder la pregunta b2' title='a2b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row21_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='01' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='02' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='03' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='04' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='05' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='06' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='07' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='08' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='09' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='10' onClick="marcarSeleccion('objVals33row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row21_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='99' onClick="marcarSeleccion('objVals33row21_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row22_1' class='padding5' style="display:none"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row22_2' class='padding5' style="display:none">¿Cómo califica la calidad de las Visitas en campo realizadas por el personal de proyectos?</div><INPUT type='hidden' name='objVals33row22_' id='objVals33row22_' value='1' lang='Por favor responder la pregunta b3' title='a2b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row22_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='01' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='02' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='03' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='04' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='05' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='06' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='07' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='08' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='09' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='10' onClick="marcarSeleccion('objVals33row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row22_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b3' id='a2b3' lang='' value='99' onClick="marcarSeleccion('objVals33row22_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row23_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row23_2' class='padding5' style="display:none">¿Cómo califica la calidad de la información incluida en los correos electrónicos del personal de proyectos?</div><INPUT type='hidden' name='objVals33row23_' id='objVals33row23_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row23_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals33row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row23_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals33row23_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row24_1' class='padding5' style="display:none"><B>d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row24_2' class='padding5' style="display:none">¿Cómo califica la calidad del Portal/Internet?</div><INPUT type='hidden' name='objVals33row24_' id='objVals33row24_' value='1' lang='Por favor responder la pregunta d' title='a2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row24_3' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='01' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_4' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='02' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_5' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='03' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_6' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='04' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_7' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='05' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_8' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='06' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_9' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='07' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_10' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='08' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_11' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='09' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_12' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='10' onClick="marcarSeleccion('objVals33row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row24_13' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='99' onClick="marcarSeleccion('objVals33row24_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s33row25_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s33row25_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en los proyectos ejecutados por la Superintendencia de Proyectos (SPY) – GTT. Qué le gustaría ver? O Qué está haciendo falta para lograr los objetivos o el cumplimiento de los acuerdos con el personal de la SPY?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s33row26_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s33row26_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row26_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row27_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row27_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los procesos (Alcance, tiempo, costo, riesgos y calidad) de los proyectos?</div><INPUT type='hidden' name='objVals33row27_' id='objVals33row27_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row27_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals33row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row27_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals33row27_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s33row29_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s33row29_2' class='padding5'>En relación con los proyectos ejecutados por la SPY-GTT, en una escala de 1 a 10 donde 1 es malo y 10 excelente…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row29_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row30_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row30_2' class='padding5' style="display:block">Calidad general de la ejecución de los proyectos</div><INPUT type='hidden' name='objVals33row30_' id='objVals33row30_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals33row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals33row30_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s33row31_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s33row31_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s33row31_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row32_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row32_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals33row32_' id='objVals33row32_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals33row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals33row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row33_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row33_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que los lideran</div><INPUT type='hidden' name='objVals33row33_' id='objVals33row33_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row33_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals33row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row33_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals33row33_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row34_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row34_2' class='padding5' style="display:block">Claridad de la información suministrada por el equipo de los proyectos</div><INPUT type='hidden' name='objVals33row34_' id='objVals33row34_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row34_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals33row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row34_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals33row34_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row35_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row35_2' class='padding5' style="display:block">Cumplimiento de los acuerdos sobre el alcance aprobado y los tiempos de ejecución de los proyectos</div><INPUT type='hidden' name='objVals33row35_' id='objVals33row35_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row35_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals33row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row35_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals33row35_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row36_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row36_2' class='padding5' style="display:block">Uso de herramientas tecnológicas o de métodos de trabajo de punta</div><INPUT type='hidden' name='objVals33row36_' id='objVals33row36_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row36_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals33row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row36_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals33row36_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row37_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row37_2' class='padding5' style="display:block">Cumplimiento de las directrices corporativas de HSE, Sociales, ambientales, seguridad de procesos, etc.</div><INPUT type='hidden' name='objVals33row37_' id='objVals33row37_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row37_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals33row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row37_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals33row37_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row38_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row38_2' class='padding5' style="display:block">Proceso de entrega del proyecto, entrega completa y sin pendientes o con los pendientes solucionados por el proyecto</div><INPUT type='hidden' name='objVals33row38_' id='objVals33row38_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row38_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals33row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row38_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals33row38_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row39_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row39_2' class='padding5' style="display:block">La ejecución de los proyectos estuvo acorde a las necesidades de la planta/línea</div><INPUT type='hidden' name='objVals33row39_' id='objVals33row39_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row39_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals33row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row39_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals33row39_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row40_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row40_2' class='padding5' style="display:block">Valor generado o que va a generarle los proyectos de la SPY-GTT a la planta/línea</div><INPUT type='hidden' name='objVals33row40_' id='objVals33row40_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s33row40_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals33row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s33row40_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals33row40_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row42_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row42_2' class='padding5'>Usted diría que su relación con la SPY-GTT…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s33row42_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s33row44_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s33row44_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante de la ejecución de proyectos de la SPY-GTT?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s33row45_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s33row45_3' class='padding5' style="display:block">¿Qué se está haciendo bien la ejecución de proyectos de la SPY-GTT?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s33row46_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s33row46_3' class='padding5' style="display:block">¿Qué se debe mejorar en la ejecución de proyectos de la SPY-GTT?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s33row48_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s33row48_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s33row48_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s33row48_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row49_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s33row49_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals33row49_' id='objVals33row49_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s33row49_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals33row49_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s33row49_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals33row49_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>