<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s30row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s30row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s30row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s30row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row6_2' class='padding5' style="display:block">Cómo califica la calidad de los servicios que ofrece la GCP</div><INPUT type='hidden' name='objVals30row6_' id='objVals30row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals30row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s30row8_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s30row8_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s30row8_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s30row8_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row9_1' class='padding5' style="display:block"><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row9_2' class='padding5' style="display:block">Sabe usted como comunicarse con GCP dado que tenga una observación o una solicitud específica sobre el servicio que recibe?</div><INPUT type='hidden' name='objVals30row9_' id='objVals30row9_' value='0' lang='Por favor responder la pregunta a11' title='a11'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s30row9_3' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='1' onClick="marcarSeleccion('objVals30row9_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s30row9_4' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='2' onClick="marcarSeleccion('objVals30row9_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s30row10_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s30row10_2' class='padding5'>En general su relación con las personas del GCP es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s30row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s30row16_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s30row11_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s30row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s30row17_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s30row12_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s30row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s30row18_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s30row13_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s30row14_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj14' value='40' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s30row19_','a2d');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s30row14_2' class='padding2'>Herramientas internas de tecnología de la GCP </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s30row15_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s30row15_2' class='padding5'>Teniendo en cuenta la atención brindada por GCP, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row15_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row16_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row16_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals30row16_' id='objVals30row16_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals30row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals30row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row17_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals30row17_' id='objVals30row17_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals30row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals30row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row18_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row18_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals30row18_' id='objVals30row18_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row18_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals30row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row18_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals30row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row19_1' class='padding5' style="display:none"><B>d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row19_2' class='padding5' style="display:none">¿Cómo califica la calidad de las Herramientas internas de tecnología de la GCP?</div><INPUT type='hidden' name='objVals30row19_' id='objVals30row19_' value='1' lang='Por favor responder la pregunta d' title='a2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row19_3' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='01' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_4' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='02' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_5' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='03' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_6' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='04' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_7' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='05' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_8' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='06' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_9' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='07' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_10' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='08' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_11' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='09' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_12' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='10' onClick="marcarSeleccion('objVals30row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row19_13' class='padding5' style="display:none"><INPUT type='radio' name='a2d' id='a2d' lang='' value='99' onClick="marcarSeleccion('objVals30row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s30row20_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s30row20_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en GCP? Qué le gustaría ver? O Qué está haciendo falta para lograr sus objetivos o el cumplimiento de sus acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s30row21_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s30row21_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row21_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row22_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row22_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los servicios prestados por la GCP?</div><INPUT type='hidden' name='objVals30row22_' id='objVals30row22_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row22_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals30row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row22_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals30row22_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s30row24_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s30row24_2' class='padding5'>Por favor califique los siguientes aspectos en una escala de 1 a 10 donde 1 es malo y 10 excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s30row24_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row25_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row25_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals30row25_' id='objVals30row25_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals30row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals30row25_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row26_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row26_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals30row26_' id='objVals30row26_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals30row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals30row26_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row27_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row27_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals30row27_' id='objVals30row27_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals30row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals30row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row28_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row28_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals30row28_' id='objVals30row28_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals30row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals30row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row29_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row29_2' class='padding5' style="display:block">Herramientas tecnológicas como la central de información y marcación.</div><INPUT type='hidden' name='objVals30row29_' id='objVals30row29_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals30row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals30row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row30_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row30_2' class='padding5' style="display:block">Utilidad para generar acciones e informes</div><INPUT type='hidden' name='objVals30row30_' id='objVals30row30_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals30row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals30row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row31_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row31_2' class='padding5' style="display:block">Oportunidad en el reporte de hallazgo de novedades durante la inspección de GCP.</div><INPUT type='hidden' name='objVals30row31_' id='objVals30row31_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals30row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals30row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row32_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row32_2' class='padding5' style="display:block">Como considera usted que es el aporte de los recorridos de línea para la integridad y  confiabilidad de los ductos.</div><INPUT type='hidden' name='objVals30row32_' id='objVals30row32_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals30row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals30row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row33_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row33_2' class='padding5' style="display:block">Como califica el acompañamiento a las operaciones de mantenimiento y operación.</div><INPUT type='hidden' name='objVals30row33_' id='objVals30row33_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s30row33_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals30row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s30row33_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals30row33_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row35_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row35_2' class='padding5'>Usted diría que su relación con la GCP…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s30row35_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s30row37_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s30row37_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante de la GCP?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s30row38_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s30row38_3' class='padding5' style="display:block">¿Qué se está haciendo bien la GCP?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s30row39_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s30row39_3' class='padding5' style="display:block">¿Qué se debe mejorar en la GCP?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s30row41_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s30row41_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s30row41_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s30row41_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row42_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s30row42_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals30row42_' id='objVals30row42_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s30row42_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals30row42_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s30row42_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals30row42_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>