<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s91row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s91row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>&nbsp;</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s91row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s91row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row6_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row6_2' class='padding5' style="display:block">¿Cómo califica la calidad general de los servicios que le ofrece la vicepresidencia de Estrategia y Crecimiento - <B>VEC</B>…?</div><INPUT type='hidden' name='objVals91row6_' id='objVals91row6_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row6_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals91row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row6_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals91row6_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row7_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row7_2' class='padding5' style="display:block">¿Cómo califica el rol de gatekeeper que maneja DPY?</div><INPUT type='hidden' name='objVals91row7_' id='objVals91row7_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row7_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals91row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row7_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals91row7_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row8_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row8_2' class='padding5' style="display:block">¿Cómo califica la calidad general del proceso de Nuevos Negocios de Exploración & Producción - <B>GNN</B>?</div><INPUT type='hidden' name='objVals91row8_' id='objVals91row8_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row8_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals91row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row8_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals91row8_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row9_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row9_2' class='padding5' style="display:block">Cómo califica la calidad general de la Dirección Estratégica de Abastecimiento - <B>DEA</B>?</div><INPUT type='hidden' name='objVals91row9_' id='objVals91row9_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row9_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals91row9_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row9_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals91row9_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row10_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row10_2' class='padding5' style="display:block">¿Cómo califica en general a la Vicepresidencia Jurídica - <B>VIJ</B>?</div><INPUT type='hidden' name='objVals91row10_' id='objVals91row10_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row10_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals91row10_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row10_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals91row10_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row11_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row11_2' class='padding5' style="display:block">¿Cómo califica en general a la  Vicepresidencia Corporativa de Finanzas - <B>VIF</B>?</div><INPUT type='hidden' name='objVals91row11_' id='objVals91row11_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row11_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals91row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row11_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals91row11_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row12_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row12_2' class='padding5' style="display:block">¿Cómo califica en general a la  Vicepresidencia Innovación y Tecnología -<B>VIN</B>?</div><INPUT type='hidden' name='objVals91row12_' id='objVals91row12_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row12_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals91row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row12_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals91row12_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row13_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row13_2' class='padding5' style="display:block">¿Cómo califica en general al <B>ICP</B>?</div><INPUT type='hidden' name='objVals91row13_' id='objVals91row13_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row13_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals91row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row13_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals91row13_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row14_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row14_2' class='padding5' style="display:block">Cómo califica la calidad del direccionamiento y el Programa Empresarial de <B>Gestión de Conocimiento</B> en ECOPETROL S.A.?</div><INPUT type='hidden' name='objVals91row14_' id='objVals91row14_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row14_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals91row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row14_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals91row14_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row15_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row15_2' class='padding5' style="display:block">Cómo califica la calidad del acompañamiento que realiza el ICP frente a la identificación y definición de las <B>necesidades técnicas del negocio</B> a través de los Talleres de Planeación Tecnológica?</div><INPUT type='hidden' name='objVals91row15_' id='objVals91row15_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row15_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals91row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row15_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals91row15_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s91row16_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s91row16_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row16_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row17_1' class='padding5' style="display:block"><B>b11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row17_2' class='padding5' style="display:block">Cómo califica la calidad del direccionamiento y la planeación de la gestión de <B>Estandarización Técnica</B> que se viene adelantando en Ecopetrol S.A.?</div><INPUT type='hidden' name='objVals91row17_' id='objVals91row17_' value='0' lang='Por favor responder la pregunta b11' title='b11'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row17_3' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='01' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_4' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='02' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_5' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='03' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_6' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='04' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_7' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='05' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_8' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='06' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_9' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='07' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_10' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='08' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_11' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='09' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_12' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='10' onClick="marcarSeleccion('objVals91row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row17_13' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='99' onClick="marcarSeleccion('objVals91row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row18_1' class='padding5' style="display:block"><B>b12.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row18_2' class='padding5' style="display:block">¿Cómo califica en general a <B>DTI</B>?</div><INPUT type='hidden' name='objVals91row18_' id='objVals91row18_' value='0' lang='Por favor responder la pregunta b12' title='b12'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row18_3' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='01' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_4' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='02' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_5' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='03' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_6' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='04' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_7' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='05' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_8' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='06' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_9' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='07' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_10' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='08' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_11' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='09' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_12' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='10' onClick="marcarSeleccion('objVals91row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row18_13' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='99' onClick="marcarSeleccion('objVals91row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row19_1' class='padding5' style="display:block"><B>b13.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row19_2' class='padding5' style="display:block">¿Cómo califica en general a la Vicepresidencia de HSE y Sostenibilidad Operativa <B>VHS</B>?</div><INPUT type='hidden' name='objVals91row19_' id='objVals91row19_' value='0' lang='Por favor responder la pregunta b13' title='b13'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row19_3' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='01' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_4' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='02' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_5' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='03' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_6' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='04' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_7' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='05' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_8' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='06' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_9' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='07' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_10' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='08' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_11' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='09' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_12' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='10' onClick="marcarSeleccion('objVals91row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row19_13' class='padding5' style="display:block"><INPUT type='radio' name='b13' id='b13' lang='' value='99' onClick="marcarSeleccion('objVals91row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row20_1' class='padding5' style="display:block"><B>b14.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row20_2' class='padding5' style="display:block">¿Cómo califica en general a la Dirección de Gestión Social - <B>DGS</B>?</div><INPUT type='hidden' name='objVals91row20_' id='objVals91row20_' value='0' lang='Por favor responder la pregunta b14' title='b14'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row20_3' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='01' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_4' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='02' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_5' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='03' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_6' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='04' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_7' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='05' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_8' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='06' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_9' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='07' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_10' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='08' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_11' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='09' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_12' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='10' onClick="marcarSeleccion('objVals91row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row20_13' class='padding5' style="display:block"><INPUT type='radio' name='b14' id='b14' lang='' value='99' onClick="marcarSeleccion('objVals91row20_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row21_1' class='padding5' style="display:block"><B>b15.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row21_2' class='padding5' style="display:block">¿Cómo califica en general a la Dirección de Seguridad Física - <B>DSF</B>?</div><INPUT type='hidden' name='objVals91row21_' id='objVals91row21_' value='0' lang='Por favor responder la pregunta b15' title='b15'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row21_3' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='01' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_4' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='02' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_5' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='03' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_6' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='04' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_7' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='05' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_8' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='06' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_9' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='07' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_10' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='08' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_11' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='09' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_12' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='10' onClick="marcarSeleccion('objVals91row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row21_13' class='padding5' style="display:block"><INPUT type='radio' name='b15' id='b15' lang='' value='99' onClick="marcarSeleccion('objVals91row21_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row22_1' class='padding5' style="display:block"><B>b16.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row22_2' class='padding5' style="display:block">¿Cómo califica en general a la Dirección de HSE - <B>DHS</B>?</div><INPUT type='hidden' name='objVals91row22_' id='objVals91row22_' value='0' lang='Por favor responder la pregunta b16' title='b16'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row22_3' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='01' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_4' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='02' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_5' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='03' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_6' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='04' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_7' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='05' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_8' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='06' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_9' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='07' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_10' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='08' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_11' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='09' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_12' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='10' onClick="marcarSeleccion('objVals91row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row22_13' class='padding5' style="display:block"><INPUT type='radio' name='b16' id='b16' lang='' value='99' onClick="marcarSeleccion('objVals91row22_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row23_1' class='padding5' style="display:block"><B>b17.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row23_2' class='padding5' style="display:block">¿Cómo califica en general a la Vicepresidencia de Transporte y Logística <B>VIT</B></div><INPUT type='hidden' name='objVals91row23_' id='objVals91row23_' value='0' lang='Por favor responder la pregunta b17' title='b17'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row23_3' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='01' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_4' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='02' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_5' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='03' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_6' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='04' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_7' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='05' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_8' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='06' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_9' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='07' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_10' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='08' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_11' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='09' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_12' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='10' onClick="marcarSeleccion('objVals91row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row23_13' class='padding5' style="display:block"><INPUT type='radio' name='b17' id='b17' lang='' value='99' onClick="marcarSeleccion('objVals91row23_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row24_1' class='padding5' style="display:block"><B>b18.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row24_2' class='padding5' style="display:block">¿Cómo califica en general a la Dirección de Servicios Compartidos - <B>DSC</B>?</div><INPUT type='hidden' name='objVals91row24_' id='objVals91row24_' value='0' lang='Por favor responder la pregunta b18' title='b18'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row24_3' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='01' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_4' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='02' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_5' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='03' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_6' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='04' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_7' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='05' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_8' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='06' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_9' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='07' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_10' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='08' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_11' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='09' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_12' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='10' onClick="marcarSeleccion('objVals91row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row24_13' class='padding5' style="display:block"><INPUT type='radio' name='b18' id='b18' lang='' value='99' onClick="marcarSeleccion('objVals91row24_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row25_1' class='padding5' style="display:block"><B>b19.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row25_2' class='padding5' style="display:block">¿Cómo califica el proceso general de gestión de los Ejecutivos de Cuenta de la Dirección de Servicios Compartidos - DSC?</div><INPUT type='hidden' name='objVals91row25_' id='objVals91row25_' value='0' lang='Por favor responder la pregunta b19' title='b19'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='01' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='02' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='03' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='04' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='05' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='06' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='07' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='08' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='09' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='10' onClick="marcarSeleccion('objVals91row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b19' id='b19' lang='' value='99' onClick="marcarSeleccion('objVals91row25_');" /></div></TD>
				 </TR><TR><TD align='left' colspan='15' valign='top'><TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0'>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>Madurez de Procesos</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s91row28_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s91row28_2' class='padding5'>Cuál de las siguientes descripciones define el estado de:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='2'  nowrap='nowrap'><div id='s91row28_3' class='padding2'>Se han reconocido<br />los problemas,<br />no existen procesos<br />estándar para<br />solucionarlos,<br />las soluciones son<br />específicas o propias.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2'  nowrap='nowrap'><div id='s91row28_4' class='padding2'>La gestión de la<br />organización<br />se realiza por<br />dependencias y se<br />documentan<br />procesos por<br />requisito del<br />SGC.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2'  nowrap='nowrap'><div id='s91row28_5' class='padding2'>Los procesos están<br />alineados con la<br />estrategia y se han<br />estandarizado<br />documentado<br />y difundido<br />y los colaboradores<br />inician su utilización.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2'  nowrap='nowrap'><div id='s91row28_6' class='padding2'>Se mide y monitorea<br />el desempeño de los<br />procesos (no áreas) y se<br />mejoran continuamente.<br />Los colaboradores<br />ejecutan su proceso<br />de manera sistemática.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2'  nowrap='nowrap'><div id='s91row28_7' class='padding2'>Se demuestra que<br />el proceso ha<br />contribuido con el<br />logro de la estrategia<br />y es una mejor práctica<br />comparable o superior<br />con la industria mundial.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2'  nowrap='nowrap'><div id='s91row28_8' class='padding2'>NS/NR</div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s91row29_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s91row29_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_3' class='padding2'>1</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_12' class='padding2'>10</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s91row29_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row30_1' class='padding5' style="display:block"><B>m1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row30_2' class='padding5' style="display:block">Su macroproceso.</div><INPUT type='hidden' name='objVals91row30_' id='objVals91row30_' value='0' lang='Por favor responder la pregunta m1' title='m1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row30_3' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='01' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_4' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='02' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_5' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='03' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_6' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='04' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_7' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='05' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_8' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='06' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_9' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='07' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_10' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='08' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_11' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='09' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_12' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='10' onClick="marcarSeleccion('objVals91row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row30_13' class='padding5' style="display:block"><INPUT type='radio' name='m1' id='m1' lang='' value='99' onClick="marcarSeleccion('objVals91row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row31_1' class='padding5' style="display:block"><B>m2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row31_2' class='padding5' style="display:block">Gestión del Abastecimiento</div><INPUT type='hidden' name='objVals91row31_' id='objVals91row31_' value='0' lang='Por favor responder la pregunta m2' title='m2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row31_3' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='01' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_4' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='02' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_5' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='03' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_6' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='04' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_7' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='05' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_8' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='06' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_9' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='07' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_10' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='08' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_11' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='09' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_12' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='10' onClick="marcarSeleccion('objVals91row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row31_13' class='padding5' style="display:block"><INPUT type='radio' name='m2' id='m2' lang='' value='99' onClick="marcarSeleccion('objVals91row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row32_1' class='padding5' style="display:block"><B>m3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row32_2' class='padding5' style="display:block">Gestión del Talento Humano</div><INPUT type='hidden' name='objVals91row32_' id='objVals91row32_' value='0' lang='Por favor responder la pregunta m3' title='m3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row32_3' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='01' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_4' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='02' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_5' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='03' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_6' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='04' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_7' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='05' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_8' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='06' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_9' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='07' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_10' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='08' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_11' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='09' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_12' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='10' onClick="marcarSeleccion('objVals91row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row32_13' class='padding5' style="display:block"><INPUT type='radio' name='m3' id='m3' lang='' value='99' onClick="marcarSeleccion('objVals91row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row33_1' class='padding5' style="display:block"><B>m4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row33_2' class='padding5' style="display:block">Gestión del Tecnología de Información</div><INPUT type='hidden' name='objVals91row33_' id='objVals91row33_' value='0' lang='Por favor responder la pregunta m4' title='m4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row33_3' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='01' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_4' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='02' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_5' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='03' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_6' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='04' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_7' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='05' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_8' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='06' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_9' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='07' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_10' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='08' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_11' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='09' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_12' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='10' onClick="marcarSeleccion('objVals91row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row33_13' class='padding5' style="display:block"><INPUT type='radio' name='m4' id='m4' lang='' value='99' onClick="marcarSeleccion('objVals91row33_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row34_1' class='padding5' style="display:block"><B>m5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s91row34_2' class='padding5' style="display:block">Gestión de Servicios Jurídicos</div><INPUT type='hidden' name='objVals91row34_' id='objVals91row34_' value='0' lang='Por favor responder la pregunta m5' title='m5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s91row34_3' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='01' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_4' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='02' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_5' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='03' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_6' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='04' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_7' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='05' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_8' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='06' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_9' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='07' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_10' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='08' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_11' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='09' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_12' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='10' onClick="marcarSeleccion('objVals91row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s91row34_13' class='padding5' style="display:block"><INPUT type='radio' name='m5' id='m5' lang='' value='99' onClick="marcarSeleccion('objVals91row34_');" /></div></TD>
				 </TR></TABLE></TD></TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>