<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s44row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s44row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>OBJETIVO DEL PROCESO/AREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s44row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s44row5_2' class='padding5'>Garantizar  la viabilidad y continuidad de la operación y de los proyectos a través de la protección a las personas y la  infraestructura, enmarcados en los principios voluntarios en seguridad y derechos humanos.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s44row7_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s44row7_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row7_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row8_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row8_2' class='padding5' style="display:block">Cómo califica la calidad general de los servicios y apoyos de la Dirección de Seguridad Física - DSF</div><INPUT type='hidden' name='objVals44row8_' id='objVals44row8_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row8_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row8_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals44row8_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s44row10_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s44row10_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s44row10_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s44row10_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row11_1' class='padding5' style="display:block"><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row11_2' class='padding5' style="display:block">Sabe usted como comunicase con la Dirección de Seguridad Física dado que tenga una observación o una solicitud específica sobre el servicio que recibe?</div><INPUT type='hidden' name='objVals44row11_' id='objVals44row11_' value='0' lang='Por favor responder la pregunta a11' title='a11'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s44row11_3' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='1' onClick="marcarSeleccion('objVals44row11_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s44row11_4' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='2' onClick="marcarSeleccion('objVals44row11_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s44row12_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s44row12_2' class='padding5'>En general su relación con las personas de la Dirección de Seguridad Física es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s44row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s44row18_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s44row13_2' class='padding2'>Telefónicamente a través de los Command Center  </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s44row14_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj14' value='21' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s44row19_','a2b1');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s44row14_2' class='padding2'>Líderes, profesionales y analistas de Seguridad de cada regional </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s44row15_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj15' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s44row20_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s44row15_2' class='padding2'>Correo electrónico al Buzón de la Dirección de Seguridad Física </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s44row16_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj16' value='22' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s44row21_','a2b2');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s44row16_2' class='padding2'>Personas en los controles de acceso (recepcionistas ) </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s44row17_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s44row17_2' class='padding5'>Teniendo en cuenta la atención brindada, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row17_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row18_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row18_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals44row18_' id='objVals44row18_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row18_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals44row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row18_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals44row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row19_1' class='padding5' style="display:none"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row19_2' class='padding5' style="display:none">¿Cómo califica la calidad de los Líderes, profesionales y analistas de Seguridad</div><INPUT type='hidden' name='objVals44row19_' id='objVals44row19_' value='1' lang='Por favor responder la pregunta b1' title='a2b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row19_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='01' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='02' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='03' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='04' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='05' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='06' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='07' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='08' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='09' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='10' onClick="marcarSeleccion('objVals44row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row19_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b1' id='a2b1' lang='' value='99' onClick="marcarSeleccion('objVals44row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row20_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row20_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals44row20_' id='objVals44row20_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row20_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals44row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row20_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals44row20_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row21_1' class='padding5' style="display:none"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row21_2' class='padding5' style="display:none">¿Cómo califica la calidad del personal en los controles de acceso?</div><INPUT type='hidden' name='objVals44row21_' id='objVals44row21_' value='1' lang='Por favor responder la pregunta b2' title='a2b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row21_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='01' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='02' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='03' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='04' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='05' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='06' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='07' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='08' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='09' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='10' onClick="marcarSeleccion('objVals44row21_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row21_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b2' id='a2b2' lang='' value='99' onClick="marcarSeleccion('objVals44row21_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s44row22_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s44row22_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row22_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row23_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row23_2' class='padding5' style="display:block">¿Qué tanto diria usted que conoce a la Dirección de Seguridad Física?</div><INPUT type='hidden' name='objVals44row23_' id='objVals44row23_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row23_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals44row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row23_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals44row23_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s44row24_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s44row24_3' class='padding5' style="display:block">¿Qué servicios conoce usted que presta Seguridad Física?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s44row26_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s44row26_2' class='padding5'>En relación a la atención brindada por DSF, en una escala de 1 a 10 donde 1 es malo y 10 excelente…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row26_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row27_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row27_2' class='padding5' style="display:block">Calidad general de los servicios de Seguridad Física</div><INPUT type='hidden' name='objVals44row27_' id='objVals44row27_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals44row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals44row27_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s44row28_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s44row28_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s44row28_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row29_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row29_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals44row29_' id='objVals44row29_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals44row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals44row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row30_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row30_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas de la Dirección de Seguridad Física</div><INPUT type='hidden' name='objVals44row30_' id='objVals44row30_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row30_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals44row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row30_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals44row30_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row31_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row31_2' class='padding5' style="display:block">Claridad de la información recibida</div><INPUT type='hidden' name='objVals44row31_' id='objVals44row31_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals44row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals44row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row32_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row32_2' class='padding5' style="display:block">Efectividad de la atención y coordinación</div><INPUT type='hidden' name='objVals44row32_' id='objVals44row32_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s44row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals44row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s44row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals44row32_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row34_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row34_2' class='padding5'>Usted diría que su relación con la Dirección de Seguridad Física…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s44row34_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s44row36_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s44row36_3' class='padding5' style="display:block">Para usted, ¿qué es lo más importante de las coordinaciones o servicios que realiza la Dirección de Seguridad Física?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s44row37_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s44row37_3' class='padding5' style="display:block">¿Qué se está haciendo bien la Dirección de Seguridad Física?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s44row38_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s44row38_3' class='padding5' style="display:block">¿Qué se debe mejorar en la Dirección de Seguridad Física?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s44row40_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s44row40_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s44row40_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s44row40_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row41_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s44row41_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals44row41_' id='objVals44row41_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s44row41_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals44row41_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s44row41_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals44row41_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>