<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s40row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s40row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row6_2' class='padding5' style="display:block">Cómo califica la calidad general de la Vicepresidencia Corporativa de Finanzas (VIF)</div><INPUT type='hidden' name='objVals40row6_' id='objVals40row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals40row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>VICEPRESIDENCIA CORPORATIVA DE FINANZAS</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row8_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s40row8_2' class='padding5'>Con cuáles de las siguientes áreas o servicios de la Vicepresidencia Corporativa de Finanzas (VIF) se ha relacionado:</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row9_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s40row9_2' class='padding5'><B>UNIDAD</B></div><INPUT type='hidden' name='objValAreas' id='objValAreas' value='0' lang='Por favor señalar las áreas con la que se ha relacionado'></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='15'  nowrap='nowrap'><div id='s40row9_3' class='padding2'><B>SERVICIOS</B></div></TD>
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row10_1' class='padding2'><INPUT type='checkbox' name='areas[]' id='idObj10' value='01' lang='0' onClick="marcarSeleccion('objValAreas'); " /></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row10_2' class='padding2'>Unidad de Finanzas Corporativas</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row10_2' class='padding2'>Información o  conceptos  financieros  (WACC- Financiación), evaluación  de Capacidad  financiera  de proponentes, asesoría  en financiación de Nuevos  Negocios nuevos Proyectos, estructuración Financiera.</div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row11_1' class='padding2'><INPUT type='checkbox' name='areas[]' id='idObj11' value='02' lang='0' onClick="marcarSeleccion('objValAreas'); " /></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row11_2' class='padding2'>Unidad Corporativa de Filiales</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row11_2' class='padding2'>Acompañamiento en el proceso de estructuración de nuevos negocios, seguimiento y acompañamiento a Empresas del Grupo Empresarial.</div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row12_1' class='padding2'><INPUT type='checkbox' name='areas[]' id='idObj12' value='03' lang='0' onClick="marcarSeleccion('objValAreas'); " /></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row12_2' class='padding2'>Unidad de Tesorería</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row12_2' class='padding2'>Asesoría en Tasas de interés, asesoría en determinación de exposición de riesgos financieros, asesoría en determinación de lineamientos de inversión, asesoría en análisis de contrapartes.</div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row13_1' class='padding2'><INPUT type='checkbox' name='areas[]' id='idObj13' value='04' lang='0' onClick="marcarSeleccion('objValAreas'); " /></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row13_2' class='padding2'>Unidad Corporativa de Gestión de Riesgos Empresariales</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row13_2' class='padding2'>Asesoría  e  implementación  de financiación de riesgos (seguros  y pólizas), asesoría  en el  sistema  de gestión integral de riesgos.</div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row14_1' class='padding2'><INPUT type='checkbox' name='areas[]' id='idObj14' value='05' lang='0' onClick="marcarSeleccion('objValAreas'); " /></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row14_2' class='padding2'>Dirección Corporativa de Relacionamiento con el Inversionistas</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row14_2' class='padding2'>Atención a accionistas, revelación  de resultados  trimestrales  e información relevante, atención de requerimientos  de información sobre  la compañía.</div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row15_1' class='padding2'><INPUT type='checkbox' name='areas[]' id='idObj15' value='06' lang='0' onClick="marcarSeleccion('objValAreas'); " /></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row15_2' class='padding2'>Coordinación Corporativa de Aseguramiento SOX</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row15_2' class='padding2'>Asesoría en el cumplimiento de la Ley SOX</div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row16_1' class='padding2'><INPUT type='checkbox' name='areas[]' id='idObj16' value='07' lang='0' onClick="marcarSeleccion('objValAreas'); " /></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row16_2' class='padding2'>Grupo Control de Reservas</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row16_2' class='padding2'>Emisión de  lineamientos  en  el proceso  de auditoría de  reservas, capacitación en reservas, control de procesos de reservas, coordinación de auditorías, realización de revisiones de reservas y auditorías internas.</div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row17_1' class='padding2'><INPUT type='checkbox' name='areas[]' id='idObj17' value='08' lang='0' onClick="marcarSeleccion('objValAreas'); " /></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row17_2' class='padding2'>Coordinación Corporativa de Asesoría y Planeación Tributaria</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row17_2' class='padding2'>Conceptos  Tributarios (incluidos precios de transferencia), asesorías  tributarias, Asesoría Tributaria de Nuevos  Negocios y nuevos proyectos, Capacitación en temas  tributarios (precios de transferencia y beneficios tributarios)</div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row19_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s40row19_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s40row19_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s40row19_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row20_1' class='padding5' style="display:block"><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row20_2' class='padding5' style="display:block">Sabe usted como comunicarse con la Vicepresidencia Corporativa de Finanzas (VIF)dado que tenga una observación o una solicitud específica sobre el servicio que recibe?</div><INPUT type='hidden' name='objVals40row20_' id='objVals40row20_' value='0' lang='Por favor responder la pregunta a11' title='a11'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s40row20_3' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='1' onClick="marcarSeleccion('objVals40row20_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s40row20_4' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='2' onClick="marcarSeleccion('objVals40row20_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s40row21_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s40row21_2' class='padding5'>En general su relación con las personas de la Vicepresidencia Corporativa de Finanzas (VIF) es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row22_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj22' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s40row26_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s40row22_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row23_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj23' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s40row27_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s40row23_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s40row24_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj24' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s40row28_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s40row24_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s40row25_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s40row25_2' class='padding5'>Teniendo en cuenta la atención brindada, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row25_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row26_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row26_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals40row26_' id='objVals40row26_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row26_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals40row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row26_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals40row26_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row27_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row27_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals40row27_' id='objVals40row27_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row27_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals40row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row27_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals40row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row28_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row28_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals40row28_' id='objVals40row28_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row28_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals40row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row28_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals40row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s40row29_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s40row29_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en en la Vicepresidencia Corporativa de Finanzas (VIF)? Qué le gustaría ver? O Qué está haciendo falta para lograr sus objetivos o el cumplimiento de sus acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row30_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s40row30_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row30_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row31_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row31_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los procesos, acuerdos de nivel de servicios o en general a la Vicepresidencia Corporativa de Finanzas (VIF)?</div><INPUT type='hidden' name='objVals40row31_' id='objVals40row31_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row31_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals40row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row31_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals40row31_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row33_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s40row33_2' class='padding5'>En relación con los proyectos ejecutados por VIF, en una escala de 1 a 10 donde 1 es malo y 10 excelente…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row33_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row34_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row34_2' class='padding5' style="display:block">Calidad general de la Vicepresidencia Corporativa de Finanzas (VIF) durante la prestación del servicio</div><INPUT type='hidden' name='objVals40row34_' id='objVals40row34_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row34_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals40row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row34_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals40row34_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row35_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s40row35_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s40row35_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row36_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row36_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals40row36_' id='objVals40row36_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row36_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals40row36_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row36_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals40row36_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row37_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row37_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals40row37_' id='objVals40row37_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row37_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals40row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row37_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals40row37_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row38_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row38_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals40row38_' id='objVals40row38_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row38_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals40row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row38_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals40row38_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row39_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row39_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals40row39_' id='objVals40row39_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row39_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals40row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row39_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals40row39_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row40_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row40_2' class='padding5' style="display:block">El equipo de la VIF es riguroso y consistente con la aplicación de lineamientos (normativa interna y externa) </div><INPUT type='hidden' name='objVals40row40_' id='objVals40row40_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row40_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals40row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row40_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals40row40_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row41_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row41_2' class='padding5' style="display:block">Participación y/o acompañamiento proactivo del (proceso/área)</div><INPUT type='hidden' name='objVals40row41_' id='objVals40row41_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row41_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals40row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row41_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals40row41_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row42_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row42_2' class='padding5' style="display:block">A través de los servicios prestados transfiere el conocimientos básicos en el tema</div><INPUT type='hidden' name='objVals40row42_' id='objVals40row42_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row42_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals40row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row42_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals40row42_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row43_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row43_2' class='padding5' style="display:block">Interacción que genera valor para la toma de decisiones</div><INPUT type='hidden' name='objVals40row43_' id='objVals40row43_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row43_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals40row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row43_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals40row43_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row44_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row44_2' class='padding5' style="display:block">Los profesionales que le prestaron el servicio y/o asesoría tienen una visión integral de la compañía y sus procesos.</div><INPUT type='hidden' name='objVals40row44_' id='objVals40row44_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s40row44_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals40row44_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s40row44_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals40row44_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row46_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row46_2' class='padding5'>Usted diría que su relación con la Vicepresidencia Corporativa de Finanzas (VIF)…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s40row46_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s40row48_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s40row48_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante de la Vicepresidencia Corporativa de Finanzas (VIF)?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s40row49_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s40row49_3' class='padding5' style="display:block">¿Qué se está haciendo bien la Vicepresidencia Corporativa de Finanzas (VIF)?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s40row50_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s40row50_3' class='padding5' style="display:block">¿Qué se debe mejorar en la Vicepresidencia Corporativa de Finanzas (VIF)?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s40row52_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s40row52_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s40row52_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s40row52_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row53_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s40row53_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals40row53_' id='objVals40row53_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s40row53_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals40row53_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s40row53_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals40row53_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>