<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s29row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row6_2' class='padding5' style="display:block">Cómo califica la calidad general a la DTI– Dirección de Tecnología de Información</div><INPUT type='hidden' name='objVals29row6_' id='objVals29row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals29row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row8_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row8_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s29row8_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s29row8_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row9_1' class='padding5' style="display:block"><B>a11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row9_2' class='padding5' style="display:block">Sabe usted como comunicase con DTI dado que tenga una observación o una solicitud específica sobre los temas que le competen?</div><INPUT type='hidden' name='objVals29row9_' id='objVals29row9_' value='0' lang='Por favor responder la pregunta a11' title='a11'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s29row9_3' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='1' onClick="marcarSeleccion('objVals29row9_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s29row9_4' class='padding5' style="display:block"><INPUT type='radio' name='a11' id='a11' lang='' value='2' onClick="marcarSeleccion('objVals29row9_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s29row10_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s29row10_2' class='padding5'>En general su relación con las personas de DTI– Dirección de Tecnología de Información es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s29row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s29row15_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s29row11_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s29row12_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj12' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s29row16_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s29row12_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s29row13_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj13' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s29row17_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s29row13_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s29row14_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row14_2' class='padding5'>Teniendo en cuenta la atención brindada, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row14_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row15_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row15_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals29row15_' id='objVals29row15_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row15_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals29row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row15_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals29row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row16_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row16_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals29row16_' id='objVals29row16_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row16_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals29row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row16_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals29row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row17_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row17_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals29row17_' id='objVals29row17_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row17_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals29row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row17_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals29row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s29row18_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s29row18_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en DTI? Qué le gustaría ver? O Qué está haciendo falta para lograr sus objetivos o el cumplimiento de sus acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row19_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row19_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row19_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row20_1' class='padding5' style="display:block"><B>a4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row20_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los procesos, acuerdos de nivel de servicios o en general a la DTI?</div><INPUT type='hidden' name='objVals29row20_' id='objVals29row20_' value='0' lang='Por favor responder la pregunta a4' title='a4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row20_3' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='01' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_4' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='02' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_5' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='03' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_6' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='04' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_7' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='05' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_8' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='06' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_9' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='07' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_10' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='08' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_11' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='09' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_12' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='10' onClick="marcarSeleccion('objVals29row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row20_13' class='padding5' style="display:block"><INPUT type='radio' name='a4' id='a4' lang='' value='99' onClick="marcarSeleccion('objVals29row20_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row22_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row22_2' class='padding5'>En una escala de 1 a 10 donde 1 es malo y 10 excelente…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row22_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row23_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row23_2' class='padding5' style="display:block">Calidad general de los procesos de DTI</div><INPUT type='hidden' name='objVals29row23_' id='objVals29row23_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row23_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals29row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row23_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals29row23_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row24_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row24_2' class='padding5'>Más especificamente en cuanto a:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row24_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row25_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row25_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals29row25_' id='objVals29row25_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals29row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals29row25_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row26_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row26_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals29row26_' id='objVals29row26_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals29row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals29row26_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row27_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row27_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals29row27_' id='objVals29row27_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals29row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals29row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row28_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row28_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals29row28_' id='objVals29row28_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals29row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals29row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row29_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row29_2' class='padding5' style="display:block">Herramientas utilizadas tecnológicas, métodos y mejores prácticas </div><INPUT type='hidden' name='objVals29row29_' id='objVals29row29_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals29row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals29row29_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row30_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s29row30_2' class='padding5'>En una escala donde 1 es “no aplica o no usa” y 10 es “aplica o lo usa con frecuencia” y pensando en la <u>Gestión para la seguridad de la información</u></div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s29row31_1' class='padding5'><B>1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row31_2' class='padding5'>Cuál es su nivel de <B>uso/aplicación</B> de las siguientes prácticas de seguridad de la información</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_3' class='padding2'>1<br />No aplica<br />o no usa</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_12' class='padding2'>10<br />Aplica<br />o lo usa con<br />frecuencia</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row31_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row32_1' class='padding5' style="display:block"><B>1a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row32_2' class='padding5' style="display:block">Clasifico y hace el tratamiento la información de acuerdo con su nivel de confidencialidad</div><INPUT type='hidden' name='objVals29row32_' id='objVals29row32_' value='0' lang='Por favor responder la pregunta 1a' title='pg1a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row32_3' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='01' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_4' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='02' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_5' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='03' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_6' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='04' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_7' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='05' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_8' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='06' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_9' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='07' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_10' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='08' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_11' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='09' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_12' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='10' onClick="marcarSeleccion('objVals29row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row32_13' class='padding5' style="display:block"><INPUT type='radio' name='pg1a' id='pg1a' lang='' value='99' onClick="marcarSeleccion('objVals29row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row33_1' class='padding5' style="display:block"><B>1b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row33_2' class='padding5' style="display:block">Mantengo copias de respaldos de la información de mi equipo (correos, archivos, otros)</div><INPUT type='hidden' name='objVals29row33_' id='objVals29row33_' value='0' lang='Por favor responder la pregunta 1b' title='pg1b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row33_3' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='01' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_4' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='02' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_5' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='03' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_6' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='04' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_7' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='05' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_8' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='06' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_9' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='07' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_10' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='08' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_11' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='09' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_12' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='10' onClick="marcarSeleccion('objVals29row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row33_13' class='padding5' style="display:block"><INPUT type='radio' name='pg1b' id='pg1b' lang='' value='99' onClick="marcarSeleccion('objVals29row33_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row34_1' class='padding5' style="display:block"><B>1c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row34_2' class='padding5' style="display:block">Hago de mi puesto de trabajo un lugar seguro</div><INPUT type='hidden' name='objVals29row34_' id='objVals29row34_' value='0' lang='Por favor responder la pregunta 1c' title='pg1c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row34_3' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='01' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_4' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='02' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_5' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='03' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_6' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='04' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_7' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='05' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_8' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='06' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_9' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='07' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_10' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='08' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_11' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='09' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_12' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='10' onClick="marcarSeleccion('objVals29row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row34_13' class='padding5' style="display:block"><INPUT type='radio' name='pg1c' id='pg1c' lang='' value='99' onClick="marcarSeleccion('objVals29row34_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row35_1' class='padding5' style="display:block"><B>1d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row35_2' class='padding5' style="display:block">Identifico y sé cómo reportar  los incidentes de seguridad de la información</div><INPUT type='hidden' name='objVals29row35_' id='objVals29row35_' value='0' lang='Por favor responder la pregunta 1d' title='pg1d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row35_3' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='01' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_4' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='02' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_5' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='03' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_6' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='04' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_7' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='05' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_8' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='06' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_9' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='07' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_10' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='08' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_11' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='09' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_12' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='10' onClick="marcarSeleccion('objVals29row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row35_13' class='padding5' style="display:block"><INPUT type='radio' name='pg1d' id='pg1d' lang='' value='99' onClick="marcarSeleccion('objVals29row35_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s29row36_1' class='padding5'><B>2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row36_2' class='padding5'>En una escala de 1 a 10 donde 1 es malo y 10 es excelente.  Cómo evalúa la <B>efectividad</B> de las siguientes prácticas frente a la seguridad de la información en su trabajo:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row36_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row37_1' class='padding5' style="display:block"><B>2a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row37_2' class='padding5' style="display:block">Clasificación de la información</div><INPUT type='hidden' name='objVals29row37_' id='objVals29row37_' value='0' lang='Por favor responder la pregunta 2a' title='pg2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row37_3' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='01' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_4' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='02' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_5' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='03' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_6' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='04' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_7' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='05' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_8' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='06' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_9' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='07' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_10' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='08' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_11' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='09' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_12' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='10' onClick="marcarSeleccion('objVals29row37_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row37_13' class='padding5' style="display:block"><INPUT type='radio' name='pg2a' id='pg2a' lang='' value='99' onClick="marcarSeleccion('objVals29row37_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row38_1' class='padding5' style="display:block"><B>2b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row38_2' class='padding5' style="display:block">Gestión segura de la información de acuerdo con su nivel de Confidencialidad</div><INPUT type='hidden' name='objVals29row38_' id='objVals29row38_' value='0' lang='Por favor responder la pregunta 2b' title='pg2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row38_3' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='01' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_4' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='02' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_5' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='03' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_6' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='04' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_7' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='05' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_8' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='06' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_9' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='07' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_10' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='08' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_11' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='09' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_12' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='10' onClick="marcarSeleccion('objVals29row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row38_13' class='padding5' style="display:block"><INPUT type='radio' name='pg2b' id='pg2b' lang='' value='99' onClick="marcarSeleccion('objVals29row38_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row39_1' class='padding5' style="display:block"><B>2c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row39_2' class='padding5' style="display:block">Respaldo de la información del equipo</div><INPUT type='hidden' name='objVals29row39_' id='objVals29row39_' value='0' lang='Por favor responder la pregunta 2c' title='pg2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row39_3' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='01' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_4' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='02' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_5' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='03' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_6' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='04' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_7' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='05' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_8' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='06' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_9' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='07' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_10' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='08' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_11' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='09' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_12' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='10' onClick="marcarSeleccion('objVals29row39_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row39_13' class='padding5' style="display:block"><INPUT type='radio' name='pg2c' id='pg2c' lang='' value='99' onClick="marcarSeleccion('objVals29row39_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row40_1' class='padding5' style="display:block"><B>2d.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row40_2' class='padding5' style="display:block">Puesto de trabajo seguro</div><INPUT type='hidden' name='objVals29row40_' id='objVals29row40_' value='0' lang='Por favor responder la pregunta 2d' title='pg2d'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row40_3' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='01' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_4' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='02' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_5' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='03' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_6' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='04' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_7' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='05' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_8' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='06' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_9' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='07' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_10' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='08' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_11' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='09' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_12' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='10' onClick="marcarSeleccion('objVals29row40_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row40_13' class='padding5' style="display:block"><INPUT type='radio' name='pg2d' id='pg2d' lang='' value='99' onClick="marcarSeleccion('objVals29row40_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row41_1' class='padding5' style="display:block"><B>2e.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row41_2' class='padding5' style="display:block">Gestión de incidentes de seguridad de la información</div><INPUT type='hidden' name='objVals29row41_' id='objVals29row41_' value='0' lang='Por favor responder la pregunta 2e' title='pg2e'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row41_3' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='01' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_4' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='02' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_5' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='03' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_6' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='04' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_7' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='05' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_8' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='06' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_9' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='07' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_10' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='08' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_11' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='09' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_12' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='10' onClick="marcarSeleccion('objVals29row41_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row41_13' class='padding5' style="display:block"><INPUT type='radio' name='pg2e' id='pg2e' lang='' value='99' onClick="marcarSeleccion('objVals29row41_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row42_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row42_2' class='padding5'>En una escala donde 1 es nada y 10 es mucho</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s29row42_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row43_1' class='padding5' style="display:block"><B>3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row43_2' class='padding5' style="display:block">¿Cómo evalúa el apoyo que recibe para fortalecer y mejorar las prácticas de seguridad de la información?</div><INPUT type='hidden' name='objVals29row43_' id='objVals29row43_' value='0' lang='Por favor responder la pregunta 3' title='pg3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s29row43_3' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='01' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_4' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='02' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_5' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='03' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_6' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='04' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_7' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='05' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_8' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='06' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_9' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='07' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_10' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='08' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_11' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='09' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_12' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='10' onClick="marcarSeleccion('objVals29row43_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s29row43_13' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='99' onClick="marcarSeleccion('objVals29row43_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row45_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row45_2' class='padding5'>Usted diría que su relación con el DTI</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s29row45_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s29row47_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s29row47_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante para  DTI?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s29row48_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s29row48_3' class='padding5' style="display:block">¿Qué se está haciendo bien en la DTI?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s29row49_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s29row49_3' class='padding5' style="display:block">¿Qué se debe mejorar en la DTI?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s29row51_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s29row51_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s29row51_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s29row51_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row52_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s29row52_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals29row52_' id='objVals29row52_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s29row52_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals29row52_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s29row52_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals29row52_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>