<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='7%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s39row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PENSANDO EN SU MACROPROCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row5_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row5_3' class='padding2'>Se han reconocido los problemas, no existen procesos estándar para solucionarlos, las soluciones son específicas o propias.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row5_4' class='padding2'>La gestión de la organización se realiza por dependencias y se documentan procesos por requisito del SGC.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row5_5' class='padding2'>Los procesos están alineados con la estrategia y se han estandarizado documentado y difundido y los colaboradores inician su utilización.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row5_6' class='padding2'>Se mide y monitorea el desempeño de los procesos (no áreas) y se mejoran continuamente. Los colaboradores ejecutan su proceso de manera sistemática.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row5_7' class='padding2'>Se demuestra que el proceso ha contribuido con el logro de la estrategia y es una mejor práctica comparable o superior con la industria mundial.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row5_8' class='padding2'>NS/NR</div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row6_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row6_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_3' class='padding2'>1</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_12' class='padding2'>10</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row6_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row7_1' class='padding5' style="display:block"><B>1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row7_2' class='padding5' style="display:block">Cuál de las siguientes descripciones define el estado de su macroproceso</div><INPUT type='hidden' name='objVals39row7_' id='objVals39row7_' value='0' lang='Por favor responder la pregunta 1' title='pg1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row7_3' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='01' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_4' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='02' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_5' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='03' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_6' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='04' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_7' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='05' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_8' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='06' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_9' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='07' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_10' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='08' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_11' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='09' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_12' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='10' onClick="marcarSeleccion('objVals39row7_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row7_13' class='padding5' style="display:block"><INPUT type='radio' name='pg1' id='pg1' lang='' value='99' onClick="marcarSeleccion('objVals39row7_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row8_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s39row8_2' class='padding5'>Ahora en relación con las siguientes características cuál descripción expresa mejor la situación de su macroproceso:</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row9_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row9_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row9_3' class='padding2'>Existe y obedece exclusivamente al conocimiento de los colaboradores</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row9_4' class='padding2'>Se asocia con las áreas de la organización.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row9_5' class='padding2'>Se asocia y es diseñada e implementada en el proceso.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row9_6' class='padding2'>Se gestiona y mejora en el proceso.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row9_7' class='padding2'>Es sostenible en el proceso.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row9_8' class='padding2'>NS/NR</div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row10_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row10_2' class='padding5'>Característica</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_3' class='padding2'>1</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_12' class='padding2'>10</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row10_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row11_1' class='padding5' style="display:block"><B>2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row11_2' class='padding5' style="display:block">Alineación de los resultados de los procesos con el logro de la estrategia de la empresa.</div><INPUT type='hidden' name='objVals39row11_' id='objVals39row11_' value='0' lang='Por favor responder la pregunta 2' title='pg2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row11_3' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='01' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_4' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='02' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_5' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='03' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_6' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='04' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_7' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='05' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_8' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='06' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_9' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='07' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_10' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='08' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_11' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='09' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_12' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='10' onClick="marcarSeleccion('objVals39row11_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row11_13' class='padding5' style="display:block"><INPUT type='radio' name='pg2' id='pg2' lang='' value='99' onClick="marcarSeleccion('objVals39row11_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row12_1' class='padding5' style="display:block"><B>3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row12_2' class='padding5' style="display:block">Definición e implementación de objetivos e indicadores que permitan realizar sistemáticamente ajustes y mejoras al proceso.</div><INPUT type='hidden' name='objVals39row12_' id='objVals39row12_' value='0' lang='Por favor responder la pregunta 3' title='pg3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row12_3' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='01' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_4' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='02' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_5' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='03' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_6' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='04' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_7' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='05' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_8' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='06' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_9' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='07' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_10' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='08' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_11' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='09' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_12' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='10' onClick="marcarSeleccion('objVals39row12_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row12_13' class='padding5' style="display:block"><INPUT type='radio' name='pg3' id='pg3' lang='' value='99' onClick="marcarSeleccion('objVals39row12_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row13_1' class='padding5' style="display:block"><B>4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row13_2' class='padding5' style="display:block">Diseño del proceso con base en los requisitos del Compendio de Buenas Prácticas, según alcance definido.</div><INPUT type='hidden' name='objVals39row13_' id='objVals39row13_' value='0' lang='Por favor responder la pregunta 4' title='pg4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row13_3' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='01' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_4' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='02' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_5' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='03' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_6' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='04' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_7' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='05' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_8' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='06' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_9' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='07' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_10' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='08' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_11' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='09' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_12' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='10' onClick="marcarSeleccion('objVals39row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row13_13' class='padding5' style="display:block"><INPUT type='radio' name='pg4' id='pg4' lang='' value='99' onClick="marcarSeleccion('objVals39row13_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row14_1' class='padding5' style="display:block"><B>5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row14_2' class='padding5' style="display:block">Diseño del proceso teniendo en cuenta la legislación y otros requisitos que la organización suscriba.</div><INPUT type='hidden' name='objVals39row14_' id='objVals39row14_' value='0' lang='Por favor responder la pregunta 5' title='pg5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row14_3' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='01' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_4' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='02' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_5' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='03' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_6' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='04' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_7' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='05' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_8' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='06' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_9' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='07' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_10' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='08' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_11' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='09' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_12' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='10' onClick="marcarSeleccion('objVals39row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row14_13' class='padding5' style="display:block"><INPUT type='radio' name='pg5' id='pg5' lang='' value='99' onClick="marcarSeleccion('objVals39row14_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row15_1' class='padding5' style="display:block"><B>6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row15_2' class='padding5' style="display:block">Identificación, evaluación, implementación y monitoreo de los cambios que pueden afectar la capacidad del proceso para lograr sus resultados</div><INPUT type='hidden' name='objVals39row15_' id='objVals39row15_' value='0' lang='Por favor responder la pregunta 6' title='pg6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row15_3' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='01' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_4' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='02' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_5' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='03' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_6' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='04' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_7' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='05' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_8' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='06' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_9' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='07' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_10' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='08' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_11' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='09' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_12' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='10' onClick="marcarSeleccion('objVals39row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row15_13' class='padding5' style="display:block"><INPUT type='radio' name='pg6' id='pg6' lang='' value='99' onClick="marcarSeleccion('objVals39row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row16_1' class='padding5' style="display:block"><B>7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row16_2' class='padding5' style="display:block">Disposición sistemática de los recursos necesarios para la definición, implementación y mejoramiento del proceso, según su aporte en la estrategia.</div><INPUT type='hidden' name='objVals39row16_' id='objVals39row16_' value='0' lang='Por favor responder la pregunta 7' title='pg7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row16_3' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='01' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_4' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='02' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_5' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='03' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_6' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='04' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_7' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='05' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_8' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='06' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_9' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='07' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_10' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='08' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_11' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='09' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_12' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='10' onClick="marcarSeleccion('objVals39row16_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row16_13' class='padding5' style="display:block"><INPUT type='radio' name='pg7' id='pg7' lang='' value='99' onClick="marcarSeleccion('objVals39row16_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row17_1' class='padding5' style="display:block"><B>8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row17_2' class='padding5' style="display:block">Alineación, implementación y revisión sistemática de los roles de los procesos.</div><INPUT type='hidden' name='objVals39row17_' id='objVals39row17_' value='0' lang='Por favor responder la pregunta 8' title='pg8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row17_3' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='01' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_4' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='02' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_5' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='03' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_6' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='04' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_7' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='05' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_8' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='06' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_9' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='07' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_10' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='08' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_11' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='09' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_12' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='10' onClick="marcarSeleccion('objVals39row17_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row17_13' class='padding5' style="display:block"><INPUT type='radio' name='pg8' id='pg8' lang='' value='99' onClick="marcarSeleccion('objVals39row17_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row18_1' class='padding5' style="display:block"><B>9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row18_2' class='padding5' style="display:block">Alineación de la estructura organizacional con el diseño del proceso y la adaptación a los cambios/mejoras que se puedan presentar en el proceso.</div><INPUT type='hidden' name='objVals39row18_' id='objVals39row18_' value='0' lang='Por favor responder la pregunta 9' title='pg9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row18_3' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='01' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_4' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='02' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_5' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='03' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_6' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='04' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_7' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='05' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_8' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='06' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_9' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='07' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_10' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='08' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_11' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='09' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_12' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='10' onClick="marcarSeleccion('objVals39row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row18_13' class='padding5' style="display:block"><INPUT type='radio' name='pg9' id='pg9' lang='' value='99' onClick="marcarSeleccion('objVals39row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row19_1' class='padding5' style="display:block"><B>10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row19_2' class='padding5' style="display:block">Definición, implementación y revisión sistemática de competencias de los colaboradores para garantizar una gestión integral del proceso.</div><INPUT type='hidden' name='objVals39row19_' id='objVals39row19_' value='0' lang='Por favor responder la pregunta 10' title='pg10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row19_3' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='01' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_4' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='02' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_5' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='03' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_6' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='04' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_7' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='05' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_8' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='06' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_9' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='07' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_10' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='08' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_11' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='09' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_12' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='10' onClick="marcarSeleccion('objVals39row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row19_13' class='padding5' style="display:block"><INPUT type='radio' name='pg10' id='pg10' lang='' value='99' onClick="marcarSeleccion('objVals39row19_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row20_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row20_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row20_3' class='padding2'>Existe y obedece exclusivamente al conocimiento de los colaboradores</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row20_4' class='padding2'>Se asocia con las áreas de la organización.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row20_5' class='padding2'>Se asocia y es diseñada e implementada en el proceso.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row20_6' class='padding2'>Se gestiona y mejora en el proceso.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row20_7' class='padding2'>Es sostenible en el proceso.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row20_8' class='padding2'>NS/NR</div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row21_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row21_2' class='padding5'>Característica</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_3' class='padding2'>1</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_12' class='padding2'>10</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row21_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row22_1' class='padding5' style="display:block"><B>11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row22_2' class='padding5' style="display:block">Alineación de la tecnología de información que da respuesta a las necesidades de los procesos empresariales.</div><INPUT type='hidden' name='objVals39row22_' id='objVals39row22_' value='0' lang='Por favor responder la pregunta 11' title='pg11'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row22_3' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='01' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_4' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='02' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_5' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='03' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_6' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='04' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_7' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='05' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_8' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='06' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_9' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='07' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_10' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='08' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_11' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='09' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_12' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='10' onClick="marcarSeleccion('objVals39row22_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row22_13' class='padding5' style="display:block"><INPUT type='radio' name='pg11' id='pg11' lang='' value='99' onClick="marcarSeleccion('objVals39row22_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row23_1' class='padding5' style="display:block"><B>12.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row23_2' class='padding5' style="display:block">Cumplimiento de los atributos de confiabilidad, seguridad, completitud, oportunidad y unicidad de la información del proceso, para asegurar la toma de decisiones efectivas.</div><INPUT type='hidden' name='objVals39row23_' id='objVals39row23_' value='0' lang='Por favor responder la pregunta 12' title='pg12'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row23_3' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='01' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_4' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='02' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_5' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='03' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_6' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='04' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_7' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='05' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_8' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='06' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_9' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='07' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_10' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='08' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_11' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='09' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_12' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='10' onClick="marcarSeleccion('objVals39row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row23_13' class='padding5' style="display:block"><INPUT type='radio' name='pg12' id='pg12' lang='' value='99' onClick="marcarSeleccion('objVals39row23_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row24_1' class='padding5' style="display:block"><B>13.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row24_2' class='padding5' style="display:block">Control y coherencia de la documentación interna y externa con el diseño y operación del proceso </div><INPUT type='hidden' name='objVals39row24_' id='objVals39row24_' value='0' lang='Por favor responder la pregunta 13' title='pg13'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row24_3' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='01' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_4' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='02' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_5' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='03' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_6' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='04' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_7' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='05' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_8' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='06' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_9' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='07' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_10' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='08' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_11' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='09' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_12' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='10' onClick="marcarSeleccion('objVals39row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row24_13' class='padding5' style="display:block"><INPUT type='radio' name='pg13' id='pg13' lang='' value='99' onClick="marcarSeleccion('objVals39row24_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row25_1' class='padding5' style="display:block"><B>14.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row25_2' class='padding5' style="display:block">Control y coherencia de los registros con el diseño y operación del proceso. </div><INPUT type='hidden' name='objVals39row25_' id='objVals39row25_' value='0' lang='Por favor responder la pregunta 14' title='pg14'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row25_3' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='01' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_4' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='02' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_5' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='03' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_6' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='04' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_7' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='05' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_8' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='06' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_9' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='07' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_10' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='08' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_11' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='09' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_12' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='10' onClick="marcarSeleccion('objVals39row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row25_13' class='padding5' style="display:block"><INPUT type='radio' name='pg14' id='pg14' lang='' value='99' onClick="marcarSeleccion('objVals39row25_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row26_1' class='padding5' style="display:block"><B>15.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row26_2' class='padding5' style="display:block">Existencia de mecanismos para permitir la reanudación del proceso (cuando aplique) ante cualquier incidente.</div><INPUT type='hidden' name='objVals39row26_' id='objVals39row26_' value='0' lang='Por favor responder la pregunta 15' title='pg15'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row26_3' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='01' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_4' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='02' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_5' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='03' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_6' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='04' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_7' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='05' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_8' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='06' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_9' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='07' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_10' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='08' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_11' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='09' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_12' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='10' onClick="marcarSeleccion('objVals39row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row26_13' class='padding5' style="display:block"><INPUT type='radio' name='pg15' id='pg15' lang='' value='99' onClick="marcarSeleccion('objVals39row26_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row27_1' class='padding5' style="display:block"><B>16.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row27_2' class='padding5' style="display:block">Identificación, evaluación y tratamiento sistemático de los riesgos y controles del proceso que afectan la operación (financieros y no financieros).</div><INPUT type='hidden' name='objVals39row27_' id='objVals39row27_' value='0' lang='Por favor responder la pregunta 16' title='pg16'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row27_3' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='01' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_4' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='02' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_5' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='03' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_6' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='04' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_7' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='05' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_8' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='06' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_9' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='07' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_10' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='08' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_11' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='09' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_12' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='10' onClick="marcarSeleccion('objVals39row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row27_13' class='padding5' style="display:block"><INPUT type='radio' name='pg16' id='pg16' lang='' value='99' onClick="marcarSeleccion('objVals39row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row28_1' class='padding5' style="display:block"><B>17.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row28_2' class='padding5' style="display:block">Evaluación de la percepción de los grupos de interés del proceso y generación de acciones de mejoramiento cuando se requiera.</div><INPUT type='hidden' name='objVals39row28_' id='objVals39row28_' value='0' lang='Por favor responder la pregunta 17' title='pg17'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row28_3' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='01' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_4' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='02' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_5' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='03' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_6' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='04' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_7' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='05' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_8' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='06' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_9' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='07' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_10' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='08' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_11' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='09' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_12' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='10' onClick="marcarSeleccion('objVals39row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row28_13' class='padding5' style="display:block"><INPUT type='radio' name='pg17' id='pg17' lang='' value='99' onClick="marcarSeleccion('objVals39row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row29_1' class='padding5' style="display:block"><B>18.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row29_2' class='padding5' style="display:block">Seguimiento y mejora sistemática del desempeño de los procesos, teniendo en cuenta los objetivos, indicadores, riesgos, controles relacionados a la operación, requisitos legales,   entre otros.</div><INPUT type='hidden' name='objVals39row29_' id='objVals39row29_' value='0' lang='Por favor responder la pregunta 18' title='pg18'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row29_3' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='01' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_4' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='02' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_5' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='03' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_6' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='04' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_7' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='05' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_8' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='06' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_9' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='07' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_10' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='08' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_11' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='09' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_12' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='10' onClick="marcarSeleccion('objVals39row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row29_13' class='padding5' style="display:block"><INPUT type='radio' name='pg18' id='pg18' lang='' value='99' onClick="marcarSeleccion('objVals39row29_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row30_1' class='padding5' style="display:block"><B>19.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row30_2' class='padding5' style="display:block">Entendimiento de la contribución del proceso en el cumplimiento de la Política Integral de ECOPETROL S.A.</div><INPUT type='hidden' name='objVals39row30_' id='objVals39row30_' value='0' lang='Por favor responder la pregunta 19' title='pg19'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row30_3' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='01' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_4' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='02' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_5' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='03' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_6' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='04' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_7' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='05' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_8' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='06' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_9' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='07' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_10' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='08' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_11' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='09' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_12' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='10' onClick="marcarSeleccion('objVals39row30_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row30_13' class='padding5' style="display:block"><INPUT type='radio' name='pg19' id='pg19' lang='' value='99' onClick="marcarSeleccion('objVals39row30_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PENSANDO EN OTROS MACROPROCESOS</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row32_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row32_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row32_3' class='padding2'>Se han reconocido los problemas, no existen procesos estándar para solucionarlos, las soluciones son específicas o propias.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row32_4' class='padding2'>La gestión de la organización se realiza por dependencias y se documentan procesos por requisito del SGC.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row32_5' class='padding2'>Los procesos están alineados con la estrategia y se han estandarizado documentado y difundido y los colaboradores inician su utilización.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row32_6' class='padding2'>Se mide y monitorea el desempeño de los procesos (no áreas) y se mejoran continuamente. Los colaboradores ejecutan su proceso de manera sistemática.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row32_7' class='padding2'>Se demuestra que el proceso ha contribuido con el logro de la estrategia y es una mejor práctica comparable o superior con la industria mundial.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row32_8' class='padding2'>NS/NR</div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row33_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row33_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_3' class='padding2'>1</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_12' class='padding2'>10</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row33_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row34_1' class='padding5' style="display:block"><B>20.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row34_2' class='padding5' style="display:block">Cuál de las siguientes descripciones define el estado del macroproceso de <B>Gestión del Abastecimiento</B></div><INPUT type='hidden' name='objVals39row34_' id='objVals39row34_' value='0' lang='Por favor responder la pregunta 20' title='pg20'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row34_3' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='01' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_4' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='02' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_5' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='03' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_6' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='04' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_7' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='05' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_8' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='06' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_9' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='07' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_10' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='08' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_11' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='09' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_12' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='10' onClick="marcarSeleccion('objVals39row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row34_13' class='padding5' style="display:block"><INPUT type='radio' name='pg20' id='pg20' lang='' value='99' onClick="marcarSeleccion('objVals39row34_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s39row35_1' class='padding5' style="display:block"><B>20a.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s39row35_3' class='padding5' style="display:block">¿Que oportunidades de mejora considera usted que tiene el macroproceso?<BR /><TEXTAREA name='vb_pg20' id='vb_pg20' lang='1' title='Por favor responder la pregunta 20a' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row36_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row36_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row36_3' class='padding2'>Se han reconocido los problemas, no existen procesos estándar para solucionarlos, las soluciones son específicas o propias.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row36_4' class='padding2'>La gestión de la organización se realiza por dependencias y se documentan procesos por requisito del SGC.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row36_5' class='padding2'>Los procesos están alineados con la estrategia y se han estandarizado documentado y difundido y los colaboradores inician su utilización.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row36_6' class='padding2'>Se mide y monitorea el desempeño de los procesos (no áreas) y se mejoran continuamente. Los colaboradores ejecutan su proceso de manera sistemática.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row36_7' class='padding2'>Se demuestra que el proceso ha contribuido con el logro de la estrategia y es una mejor práctica comparable o superior con la industria mundial.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row36_8' class='padding2'>NS/NR</div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row37_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row37_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_3' class='padding2'>1</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_12' class='padding2'>10</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row37_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row38_1' class='padding5' style="display:block"><B>21.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row38_2' class='padding5' style="display:block">Cuál de las siguientes descripciones define el estado del  macroproceso de <B>Gestión del Talento Humano</B></div><INPUT type='hidden' name='objVals39row38_' id='objVals39row38_' value='0' lang='Por favor responder la pregunta 21' title='pg21'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row38_3' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='01' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_4' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='02' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_5' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='03' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_6' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='04' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_7' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='05' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_8' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='06' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_9' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='07' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_10' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='08' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_11' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='09' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_12' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='10' onClick="marcarSeleccion('objVals39row38_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row38_13' class='padding5' style="display:block"><INPUT type='radio' name='pg21' id='pg21' lang='' value='99' onClick="marcarSeleccion('objVals39row38_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s39row39_1' class='padding5' style="display:block"><B>21a.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s39row39_3' class='padding5' style="display:block">¿Que oportunidades de mejora considera usted que tiene el macroproceso?<BR /><TEXTAREA name='vb_pg21' id='vb_pg21' lang='1' title='Por favor responder la pregunta 21a' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row40_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row40_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row40_3' class='padding2'>Se han reconocido los problemas, no existen procesos estándar para solucionarlos, las soluciones son específicas o propias.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row40_4' class='padding2'>La gestión de la organización se realiza por dependencias y se documentan procesos por requisito del SGC.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row40_5' class='padding2'>Los procesos están alineados con la estrategia y se han estandarizado documentado y difundido y los colaboradores inician su utilización.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row40_6' class='padding2'>Se mide y monitorea el desempeño de los procesos (no áreas) y se mejoran continuamente. Los colaboradores ejecutan su proceso de manera sistemática.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row40_7' class='padding2'>Se demuestra que el proceso ha contribuido con el logro de la estrategia y es una mejor práctica comparable o superior con la industria mundial.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row40_8' class='padding2'>NS/NR</div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row41_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row41_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_3' class='padding2'>1</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_12' class='padding2'>10</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row41_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row42_1' class='padding5' style="display:block"><B>22.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row42_2' class='padding5' style="display:block">Cuál de las siguientes descripciones define el estado del macroproceso de <B>Gestión del Tecnología de Información</B></div><INPUT type='hidden' name='objVals39row42_' id='objVals39row42_' value='0' lang='Por favor responder la pregunta 22' title='pg22'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row42_3' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='01' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_4' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='02' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_5' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='03' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_6' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='04' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_7' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='05' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_8' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='06' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_9' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='07' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_10' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='08' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_11' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='09' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_12' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='10' onClick="marcarSeleccion('objVals39row42_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row42_13' class='padding5' style="display:block"><INPUT type='radio' name='pg22' id='pg22' lang='' value='99' onClick="marcarSeleccion('objVals39row42_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s39row43_1' class='padding5' style="display:block"><B>22a.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s39row43_3' class='padding5' style="display:block">¿Que oportunidades de mejora considera usted que tiene el macroproceso?<BR /><TEXTAREA name='vb_pg22' id='vb_pg22' lang='1' title='Por favor responder la pregunta 22a' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row44_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row44_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row44_3' class='padding2'>Se han reconocido los problemas, no existen procesos estándar para solucionarlos, las soluciones son específicas o propias.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row44_4' class='padding2'>La gestión de la organización se realiza por dependencias y se documentan procesos por requisito del SGC.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row44_5' class='padding2'>Los procesos están alineados con la estrategia y se han estandarizado documentado y difundido y los colaboradores inician su utilización.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row44_6' class='padding2'>Se mide y monitorea el desempeño de los procesos (no áreas) y se mejoran continuamente. Los colaboradores ejecutan su proceso de manera sistemática.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row44_7' class='padding2'>Se demuestra que el proceso ha contribuido con el logro de la estrategia y es una mejor práctica comparable o superior con la industria mundial.</div></TD><TD align='center' class='borderBR divInstruccion' colspan='2' ><div id='s39row44_8' class='padding2'>NS/NR</div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s39row45_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s39row45_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_3' class='padding2'>1</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_12' class='padding2'>10</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0' ><div id='s39row45_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row46_1' class='padding5' style="display:block"><B>23.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s39row46_2' class='padding5' style="display:block">Cuál de las siguientes descripciones define el estado del macroproceso de <B>Gestión de Servicios Jurídicos</B></div><INPUT type='hidden' name='objVals39row46_' id='objVals39row46_' value='0' lang='Por favor responder la pregunta 23' title='pg23'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s39row46_3' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='01' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_4' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='02' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_5' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='03' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_6' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='04' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_7' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='05' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_8' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='06' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_9' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='07' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_10' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='08' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_11' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='09' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_12' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='10' onClick="marcarSeleccion('objVals39row46_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s39row46_13' class='padding5' style="display:block"><INPUT type='radio' name='pg23' id='pg23' lang='' value='99' onClick="marcarSeleccion('objVals39row46_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s39row47_1' class='padding5' style="display:block"><B>23a.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s39row47_3' class='padding5' style="display:block">¿Que oportunidades de mejora considera usted que tiene el macroproceso?<BR /><TEXTAREA name='vb_pg23' id='vb_pg23' lang='1' title='Por favor responder la pregunta 23a' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>