<TABLE width='100%' cellspacing='0' cellpadding='0' align='center' border='0' class='borderTL'>
	 <TR>
	  <TD width='1%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='4%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	  <TD width='2%' class='borderBR'><IMG src='/imagenes/spacer.gif' width='1' height='1'></TD>
	 </TR>
	 
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>SENSIBILIZACIÓN</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s41row3_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s41row3_2' class='padding5'>Quiero iniciar agradeciéndole su tiempo, sus opiniones y el haber aceptado esta invitación del Centro Nacional de Consultoría.<br /><br />
Yo le voy a leer las preguntas tal cual como aparecen en el formulario para evitar variaciones entre un entrevistador y otro, no puedo explicar o comentar ninguna pregunta.<br /><br />
Las preguntas que le voy a hacer son muy similares entre procesos y servicios y se establecieron así para poderlas comparar.<br /><br />
Si hay alguna pregunta que no aplica o que no desea responder o cualquier otra razón, por favor dígamelo.</div></TD>
			  
			 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>PERCEPCIÓN GENERAL PROCESO/ÁREA</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s41row5_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s41row5_2' class='padding5'>Utilizando una escala de 1 a 10, donde 1 es Malo y 10 es Excelente</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row5_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row6_1' class='padding5' style="display:block"><B>g1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row6_2' class='padding5' style="display:block">Cómo califica la calidad general de la VIJ</div><INPUT type='hidden' name='objVals41row6_' id='objVals41row6_' value='0' lang='Por favor responder la pregunta g1' title='g1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row6_3' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='01' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_4' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='02' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_5' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='03' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_6' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='04' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_7' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='05' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_8' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='06' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_9' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='07' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_10' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='08' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_11' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='09' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_12' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='10' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row6_13' class='padding5' style="display:block"><INPUT type='radio' name='g1' id='g1' lang='' value='99' onClick=" marcarSeleccion('objVals41row6_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ACCESO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s41row8_1' class='padding5'><B>a1.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan='20'><div id='s41row8_2' class='padding5'>En general su relación con las personas del jurídica es a través del:</div><INPUT type='hidden' name='objVal_a1' id='objVal_a1' value='0' lang='Por favor responder la pregunta a1'></TD>
			  
			 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s41row9_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj9' value='10' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s41row13_','a2a');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s41row9_2' class='padding2'>Teléfono </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s41row10_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj10' value='20' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s41row14_','a2b');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s41row10_2' class='padding2'>Reuniones o de forma presencial </div></TD>
				 </TR>
				 <TR>
				  <TD width='30' align='right' class='bb' valign='top'><div id='s41row11_1' class='padding2'><INPUT type='checkbox' name='a1[]' id='idObj11' value='30' lang='0' onClick="marcarSeleccion('objVal_a1'); salto(this.id,this.value,'','s41row15_','a2c');" /></div></TD>
				  <TD align='left' class='borderBR' colspan='15'><div id='s41row11_2' class='padding2'>Correo electrónico </div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='borderBR divInstruccion' valign='top'><div id='s41row12_1' class='padding5'><B>a2.</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s41row12_2' class='padding5'>Teniendo en cuenta la atención brindada por Jurídica, en una escala de 1 a 10 donde 1 es malo y 10 excelente:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row12_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row13_1' class='padding5' style="display:none"><B>a.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row13_2' class='padding5' style="display:none">¿Cómo califica la atención brindada a través del teléfono?</div><INPUT type='hidden' name='objVals41row13_' id='objVals41row13_' value='1' lang='Por favor responder la pregunta a' title='a2a'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row13_3' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='01' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_4' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='02' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_5' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='03' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_6' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='04' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_7' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='05' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_8' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='06' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_9' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='07' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_10' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='08' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_11' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='09' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_12' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='10' onClick="marcarSeleccion('objVals41row13_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row13_13' class='padding5' style="display:none"><INPUT type='radio' name='a2a' id='a2a' lang='' value='99' onClick="marcarSeleccion('objVals41row13_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row14_1' class='padding5' style="display:none"><B>b.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row14_2' class='padding5' style="display:none">¿Cómo califica la calidad de las reuniones o encuentros presenciales?</div><INPUT type='hidden' name='objVals41row14_' id='objVals41row14_' value='1' lang='Por favor responder la pregunta b' title='a2b'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row14_3' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='01' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_4' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='02' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_5' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='03' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_6' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='04' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_7' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='05' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_8' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='06' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_9' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='07' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_10' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='08' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_11' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='09' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_12' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='10' onClick="marcarSeleccion('objVals41row14_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row14_13' class='padding5' style="display:none"><INPUT type='radio' name='a2b' id='a2b' lang='' value='99' onClick="marcarSeleccion('objVals41row14_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row15_1' class='padding5' style="display:none"><B>c.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row15_2' class='padding5' style="display:none">¿Cómo califica la calidad de los correos electrónicos?</div><INPUT type='hidden' name='objVals41row15_' id='objVals41row15_' value='1' lang='Por favor responder la pregunta c' title='a2c'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row15_3' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='01' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_4' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='02' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_5' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='03' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_6' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='04' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_7' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='05' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_8' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='06' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_9' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='07' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_10' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='08' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_11' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='09' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_12' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='10' onClick="marcarSeleccion('objVals41row15_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row15_13' class='padding5' style="display:none"><INPUT type='radio' name='a2c' id='a2c' lang='' value='99' onClick="marcarSeleccion('objVals41row15_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s41row16_1' class='padding5' style="display:block"><B>a3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s41row16_3' class='padding5' style="display:block">¿Qué espera y no ha encontrado en la Vicepresidencia de Juridica de Ecopetrol? Qué le gustaría ver? O Qué está haciendo falta para lograr sus objetivos o el cumplimiento de sus acuerdos?<BR /><TEXTAREA name='vb_a3' id='vb_a3' lang='1' title='Por favor responder la pregunta a3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s41row17_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s41row17_2' class='padding5'>Utilizando la escala de 1 a 10 donde 1 es Nada o muy poco, 7 es lo necesario y 10 es mucho, se clasificaría como conocedor experto…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_3' class='padding2'>1<br />Nada</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_9' class='padding2'>7 Lo<br />necesario</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_12' class='padding2'>10<br />Mucho</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row17_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row18_1' class='padding5' style="display:block"><B>a4_1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row18_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce los diferentes servicios presta y las temáticas que atiende la VIJ?</div><INPUT type='hidden' name='objVals41row18_' id='objVals41row18_' value='0' lang='Por favor responder la pregunta a4_1' title='a4_1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row18_3' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='01' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_4' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='02' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_5' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='03' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_6' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='04' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_7' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='05' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_8' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='06' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_9' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='07' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_10' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='08' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_11' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='09' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_12' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='10' onClick="marcarSeleccion('objVals41row18_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row18_13' class='padding5' style="display:block"><INPUT type='radio' name='a4_1' id='a4_1' lang='' value='99' onClick="marcarSeleccion('objVals41row18_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row19_1' class='padding5' style="display:block"><B>a4_2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row19_2' class='padding5' style="display:block">¿Qué tanto diría usted que conoce la forma de acceder a los servicios de VIJ?</div><INPUT type='hidden' name='objVals41row19_' id='objVals41row19_' value='0' lang='Por favor responder la pregunta a4_2' title='a4_2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row19_3' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='01' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_4' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='02' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_5' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='03' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_6' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='04' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_7' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='05' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_8' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='06' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_9' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='07' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_10' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='08' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_11' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='09' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_12' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='10' onClick="marcarSeleccion('objVals41row19_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row19_13' class='padding5' style="display:block"><INPUT type='radio' name='a4_2' id='a4_2' lang='' value='99' onClick="marcarSeleccion('objVals41row19_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row20_1' class='padding5' style="display:block"><B>a4_3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row20_2' class='padding5' style="display:block">¿Qué tanto diría usted que identifica los abogados que las diferentes unidades de la VIJ tiene asignados para atender sus necesidades?</div><INPUT type='hidden' name='objVals41row20_' id='objVals41row20_' value='0' lang='Por favor responder la pregunta a4_3' title='a4_3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row20_3' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='01' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_4' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='02' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_5' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='03' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_6' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='04' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_7' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='05' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_8' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='06' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_9' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='07' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_10' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='08' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_11' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='09' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_12' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='10' onClick="marcarSeleccion('objVals41row20_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row20_13' class='padding5' style="display:block"><INPUT type='radio' name='a4_3' id='a4_3' lang='' value='99' onClick="marcarSeleccion('objVals41row20_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>EVALUACION DEL SERVICIO</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s41row22_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s41row22_2' class='padding5'>En una escala de 1 a 10 donde 1 es malo y 10 excelente…</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row22_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row23_1' class='padding5' style="display:block"><B>b1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row23_2' class='padding5' style="display:block">Calidad general de la Regional Jurídica Norte</div><INPUT type='hidden' name='objVals41row23_' id='objVals41row23_' value='0' lang='Por favor responder la pregunta b1' title='b1'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row23_3' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='01' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_4' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='02' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_5' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='03' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_6' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='04' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_7' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='05' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_8' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='06' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_9' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='07' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_10' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='08' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_11' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='09' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_12' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='10' onClick="marcarSeleccion('objVals41row23_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row23_13' class='padding5' style="display:block"><INPUT type='radio' name='b1' id='b1' lang='' value='99' onClick="marcarSeleccion('objVals41row23_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row24_1' class='padding5' style="display:block"><B>b2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row24_2' class='padding5' style="display:block">Amabilidad de las personas y las comunicaciones</div><INPUT type='hidden' name='objVals41row24_' id='objVals41row24_' value='0' lang='Por favor responder la pregunta b2' title='b2'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row24_3' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='01' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_4' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='02' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_5' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='03' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_6' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='04' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_7' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='05' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_8' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='06' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_9' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='07' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_10' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='08' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_11' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='09' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_12' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='10' onClick="marcarSeleccion('objVals41row24_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row24_13' class='padding5' style="display:block"><INPUT type='radio' name='b2' id='b2' lang='' value='99' onClick="marcarSeleccion('objVals41row24_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row25_1' class='padding5' style="display:block"><B>b3.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row25_2' class='padding5' style="display:block">Conocimiento y experiencia de las personas que lo atienden</div><INPUT type='hidden' name='objVals41row25_' id='objVals41row25_' value='0' lang='Por favor responder la pregunta b3' title='b3'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row25_3' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='01' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_4' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='02' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_5' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='03' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_6' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='04' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_7' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='05' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_8' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='06' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_9' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='07' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_10' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='08' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_11' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='09' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_12' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='10' onClick="marcarSeleccion('objVals41row25_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row25_13' class='padding5' style="display:block"><INPUT type='radio' name='b3' id='b3' lang='' value='99' onClick="marcarSeleccion('objVals41row25_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row26_1' class='padding5' style="display:block"><B>b4.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row26_2' class='padding5' style="display:block">Claridad de la información </div><INPUT type='hidden' name='objVals41row26_' id='objVals41row26_' value='0' lang='Por favor responder la pregunta b4' title='b4'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row26_3' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='01' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_4' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='02' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_5' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='03' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_6' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='04' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_7' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='05' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_8' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='06' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_9' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='07' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_10' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='08' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_11' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='09' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_12' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='10' onClick="marcarSeleccion('objVals41row26_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row26_13' class='padding5' style="display:block"><INPUT type='radio' name='b4' id='b4' lang='' value='99' onClick="marcarSeleccion('objVals41row26_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row27_1' class='padding5' style="display:block"><B>b5.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row27_2' class='padding5' style="display:block">Cumplimiento de los acuerdos y tiempos</div><INPUT type='hidden' name='objVals41row27_' id='objVals41row27_' value='0' lang='Por favor responder la pregunta b5' title='b5'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row27_3' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='01' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_4' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='02' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_5' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='03' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_6' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='04' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_7' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='05' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_8' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='06' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_9' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='07' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_10' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='08' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_11' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='09' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_12' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='10' onClick="marcarSeleccion('objVals41row27_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row27_13' class='padding5' style="display:block"><INPUT type='radio' name='b5' id='b5' lang='' value='99' onClick="marcarSeleccion('objVals41row27_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row28_1' class='padding5' style="display:block"><B>b6.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row28_2' class='padding5' style="display:block">Nivel de actualización del marco normativo y modelos utilizados </div><INPUT type='hidden' name='objVals41row28_' id='objVals41row28_' value='0' lang='Por favor responder la pregunta b6' title='b6'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row28_3' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='01' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_4' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='02' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_5' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='03' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_6' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='04' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_7' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='05' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_8' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='06' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_9' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='07' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_10' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='08' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_11' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='09' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_12' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='10' onClick="marcarSeleccion('objVals41row28_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row28_13' class='padding5' style="display:block"><INPUT type='radio' name='b6' id='b6' lang='' value='99' onClick="marcarSeleccion('objVals41row28_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row29_1' class='padding5' style="display:block"><B>b7.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row29_2' class='padding5' style="display:block">La seguridad Juridica que la proporciona a su proceso</div><INPUT type='hidden' name='objVals41row29_' id='objVals41row29_' value='0' lang='Por favor responder la pregunta b7' title='b7'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row29_3' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='01' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_4' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='02' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_5' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='03' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_6' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='04' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_7' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='05' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_8' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='06' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_9' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='07' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_10' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='08' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_11' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='09' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_12' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='10' onClick="marcarSeleccion('objVals41row29_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row29_13' class='padding5' style="display:block"><INPUT type='radio' name='b7' id='b7' lang='' value='99' onClick="marcarSeleccion('objVals41row29_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s41row30_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s41row30_2' class='padding5'>Más específicamente en relación a la:</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_3' class='padding2'>1<br />Malo</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_4' class='padding2'>2</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_5' class='padding2'>3</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_6' class='padding2'>4</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_7' class='padding2'>5</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_8' class='padding2'>6</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_9' class='padding2'>7</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_10' class='padding2'>8</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_11' class='padding2'>9</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_12' class='padding2'>10<br />Excelente</div></TD><TD align='center' class='borderBR divInstruccion' colspan='0'  nowrap='nowrap'><div id='s41row30_13' class='padding2'>NS/NR</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row31_1' class='padding5' style="display:block"><B>b8.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row31_2' class='padding5' style="display:block">Confianza </div><INPUT type='hidden' name='objVals41row31_' id='objVals41row31_' value='0' lang='Por favor responder la pregunta b8' title='b8'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row31_3' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='01' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_4' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='02' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_5' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='03' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_6' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='04' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_7' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='05' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_8' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='06' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_9' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='07' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_10' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='08' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_11' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='09' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_12' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='10' onClick="marcarSeleccion('objVals41row31_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row31_13' class='padding5' style="display:block"><INPUT type='radio' name='b8' id='b8' lang='' value='99' onClick="marcarSeleccion('objVals41row31_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row32_1' class='padding5' style="display:block"><B>b9.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row32_2' class='padding5' style="display:block">Disponibilidad </div><INPUT type='hidden' name='objVals41row32_' id='objVals41row32_' value='0' lang='Por favor responder la pregunta b9' title='b9'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row32_3' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='01' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_4' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='02' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_5' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='03' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_6' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='04' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_7' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='05' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_8' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='06' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_9' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='07' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_10' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='08' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_11' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='09' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_12' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='10' onClick="marcarSeleccion('objVals41row32_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row32_13' class='padding5' style="display:block"><INPUT type='radio' name='b9' id='b9' lang='' value='99' onClick="marcarSeleccion('objVals41row32_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row33_1' class='padding5' style="display:block"><B>b10.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row33_2' class='padding5' style="display:block">Anticipación</div><INPUT type='hidden' name='objVals41row33_' id='objVals41row33_' value='0' lang='Por favor responder la pregunta b10' title='b10'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row33_3' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='01' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_4' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='02' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_5' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='03' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_6' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='04' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_7' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='05' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_8' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='06' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_9' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='07' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_10' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='08' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_11' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='09' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_12' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='10' onClick="marcarSeleccion('objVals41row33_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row33_13' class='padding5' style="display:block"><INPUT type='radio' name='b10' id='b10' lang='' value='99' onClick="marcarSeleccion('objVals41row33_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row34_1' class='padding5' style="display:block"><B>b11.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row34_2' class='padding5' style="display:block">Apoyo integral</div><INPUT type='hidden' name='objVals41row34_' id='objVals41row34_' value='0' lang='Por favor responder la pregunta b11' title='b11'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row34_3' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='01' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_4' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='02' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_5' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='03' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_6' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='04' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_7' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='05' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_8' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='06' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_9' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='07' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_10' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='08' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_11' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='09' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_12' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='10' onClick="marcarSeleccion('objVals41row34_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row34_13' class='padding5' style="display:block"><INPUT type='radio' name='b11' id='b11' lang='' value='99' onClick="marcarSeleccion('objVals41row34_');" /></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row35_1' class='padding5' style="display:block"><B>b12.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row35_2' class='padding5' style="display:block">Calidad con oportunidad</div><INPUT type='hidden' name='objVals41row35_' id='objVals41row35_' value='0' lang='Por favor responder la pregunta b12' title='b12'></TD>
				  <TD align='center' class='borderBR' colspan='0'><div id='s41row35_3' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='01' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_4' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='02' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_5' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='03' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_6' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='04' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_7' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='05' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_8' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='06' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_9' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='07' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_10' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='08' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_11' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='09' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_12' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='10' onClick="marcarSeleccion('objVals41row35_');" /></div></TD><TD align='center' class='borderBR' colspan='0'><div id='s41row35_13' class='padding5' style="display:block"><INPUT type='radio' name='b12' id='b12' lang='' value='99' onClick="marcarSeleccion('objVals41row35_');" /></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>RESULTADO FINAL DEL SERVICIO EN RELACIÓN A EXPECTATIVAS</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row135_1' class='padding5'><B>c1.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row135_2' class='padding5'>Usted diría que su relación con la VIJ…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s41row135_3' class='padding5'>
				<SELECT name='c1' id='c1' lang='1' title='Por favor responder la pregunta c1' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row136_1' class='padding5'><B>c2.</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row136_2' class='padding5'>Usted diría que su relación con la Regional Jurídica Norte…</div></TD>
				  <TD align='left' class='borderBR' valign='top' colspan='15'><div id='s41row136_3' class='padding5'>
				<SELECT name='c2' id='c2' lang='1' title='Por favor responder la pregunta c2' class='userText' onchange="">
				 <OPTION value='' selected>Seleccione...</OPTION>
				 <OPTION value='1'>Supera sus expectativas</OPTION><OPTION value='2'>Cumple con sus expectativas</OPTION><OPTION value='3'>Está por debajo de sus expectativas</OPTION>
				</SELECT></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>ANÁLISIS CUALITATIVO DE LO OCURRIDO</B></div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s41row145_1' class='padding5' style="display:block"><B>d1.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s41row145_3' class='padding5' style="display:block">Para usted, ¿cuál es la característica más importante de la Regional Jurídica Norte?<BR /><TEXTAREA name='vb_d1' id='vb_d1' lang='1' title='Por favor responder la pregunta d1' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s41row146_1' class='padding5' style="display:block"><B>d2.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s41row146_3' class='padding5' style="display:block">¿Qué se está haciendo bien el Regional Jurídica Norte?<BR /><TEXTAREA name='vb_d2' id='vb_d2' lang='1' title='Por favor responder la pregunta d2' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
				 <TR>
				  <TD align='left' class='bb' valign='top'><div id='s41row147_1' class='padding5' style="display:block"><B>d3.</B></div></TD>
				  <TD align='left' class='borderBR' colspan='12'><div id='s41row147_3' class='padding5' style="display:block">¿Qué se debe mejorar en el Regional Jurídica Norte?<BR /><TEXTAREA name='vb_d3' id='vb_d3' lang='1' title='Por favor responder la pregunta d3' class='borderBlue' style='width:99%; height:50px;'></TEXTAREA></div></TD>
				 </TR>
			 <TR>
			  <TD align='center' class='borderBR' colspan='15' style='background-image:url(/imagenes/cnc_menubar_gris.gif);'><div class='padding5'><B>CONFIDENCIALIDAD DE LA INFORMACION</B></div></TD>
			 </TR>
			 <TR>
			  <TD align='left' class='bb divInstruccion' valign='top'><div id='s41row170_1' class='padding5'><B>&nbsp;</B></div></TD>
			  <TD align='left' class='borderBR divInstruccion' colspan=''><div id='s41row170_2' class='padding5'>&nbsp;</div></TD>
			  <TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s41row170_3' class='padding2'>SI</div></TD><TD align='center' class='borderBR divInstruccion' colspan='6'  nowrap='nowrap'><div id='s41row170_4' class='padding2'>NO</div></TD>
			 </TR>
				 <TR>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row171_1' class='padding5' style="display:block"><B>*</B></div></TD>
				  <TD align='left' class='borderBR' valign='top'><div id='s41row171_2' class='padding5' style="display:block">Esta información es agregada y usada únicamente con propósitos estadísticos a menos que usted nos autorice compartir sus datos personales al entregar sus respuestas. ¿Nos autoriza compartir sus datos personales con los encargados del manejo del servicio que usted utilizó?</div><INPUT type='hidden' name='objVals41row171_' id='objVals41row171_' value='0' lang='Por favor responder la pregunta *' title='autoriza'></TD>
				  <TD align='center' class='borderBR' colspan='6'><div id='s41row171_3' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='1' onClick=" marcarSeleccion('objVals41row171_');" /></div></TD><TD align='center' class='borderBR' colspan='6'><div id='s41row171_4' class='padding5' style="display:block"><INPUT type='radio' name='autoriza' id='autoriza' lang='' value='2' onClick=" marcarSeleccion('objVals41row171_');" /></div></TD>
				 </TR>
	 <TR>
	  <TD colspan='15' align='center' class='borderBR'><div class='padding2'>
	  <INPUT type='submit' name='btn_enviar' id='btn_enviar' class='Button' style='padding:8px 15px;' value='Enviar'>
	  <INPUT type='hidden' name='aplicoFormGeneral' id='aplicoFormGeneral' value='0' lang='0'>
</div></TD>
	 </TR>
	</TABLE>